Repository alibaba/loongcollector, pull requests merged in 2021-12, with the labels that each got.

#25 fix-or-logic-in-docker-center
  helper/docker_center.go
  plugins/input/docker/rawstdout/input_docker_stdout.go
Labels: bug

#28 fix read static docker info without labels
  helper/docker_center.go
Labels: bug

#26 support custom hash partition
  plugins/flusher/kafka/flusher_kafka.go
Labels: enhancement

#13 add processor_base64_decoding_test
  plugins/processor/base64/decoding/processor_base64_decoding_test.go
Labels: test code

#40 fix doc image text
  docs/en/concept&designs/Overview.md
  docs/zh/concept&designs/Overview.md
Labels: documentation

#30 filter properties for skywalking v3
  CHANGELOG.md
  plugins/input/skywalkingv3/management_handle.go
Labels: enhancement

#41 Fix parent span id is incorrect
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
  plugins/input/skywalkingv2/trace_segment_handle.go
  plugins/input/skywalkingv2/trace_segment_report_handle.go
Labels: bug

#44 add dependency libs when starting on windows or linux
  Makefile
Labels: chore

#33 add input_snmp, fixed #32
  CHANGELOG.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  plugins/all/all_linux.go
  plugins/input/snmp/README.md
  plugins/input/snmp/input_snmp.go
  plugins/input/snmp/input_snmp_test.go
  vendor/github.com/gosnmp/gosnmp/.gitignore
  vendor/github.com/gosnmp/gosnmp/.golangci.yml
  vendor/github.com/gosnmp/gosnmp/AUTHORS.md
  vendor/github.com/gosnmp/gosnmp/CHANGELOG.md
  vendor/github.com/gosnmp/gosnmp/Dockerfile
  vendor/github.com/gosnmp/gosnmp/LICENSE
  vendor/github.com/gosnmp/gosnmp/Makefile
  vendor/github.com/gosnmp/gosnmp/README.md
  vendor/github.com/gosnmp/gosnmp/RELEASE.md
  vendor/github.com/gosnmp/gosnmp/asn1ber_string.go
  vendor/github.com/gosnmp/gosnmp/build_tests.sh
  vendor/github.com/gosnmp/gosnmp/go.mod
  vendor/github.com/gosnmp/gosnmp/go.sum
  vendor/github.com/gosnmp/gosnmp/goimports2
  vendor/github.com/gosnmp/gosnmp/goimports2_all
  vendor/github.com/gosnmp/gosnmp/gosnmp.go
  vendor/github.com/gosnmp/gosnmp/helper.go
  vendor/github.com/gosnmp/gosnmp/interface.go
  vendor/github.com/gosnmp/gosnmp/local_tests.sh
  vendor/github.com/gosnmp/gosnmp/marshal.go
  vendor/github.com/gosnmp/gosnmp/snmp_users.sh
  vendor/github.com/gosnmp/gosnmp/snmperror_string.go
  vendor/github.com/gosnmp/gosnmp/snmpv3authprotocol_string.go
  vendor/github.com/gosnmp/gosnmp/snmpv3privprotocol_string.go
  vendor/github.com/gosnmp/gosnmp/trap.go
  vendor/github.com/gosnmp/gosnmp/trap.md
  vendor/github.com/gosnmp/gosnmp/v3.go
  vendor/github.com/gosnmp/gosnmp/v3_testing_credentials.go
  vendor/github.com/gosnmp/gosnmp/v3_usm.go
  vendor/github.com/gosnmp/gosnmp/walk.go
Labels: enhancement

#45 fix: typo
  pluginmanager/aggregator_wrapper.go
  pluginmanager/logstore_config.go
  plugins/flusher/sls/flusher_sls.go
  plugins/flusher/statistics/flusher_statistics.go
  plugins/input/canal/input_canal.go
Labels: documentation

#49 fix snmp unit test
  plugins/input/snmp/input_snmp_test.go
Labels: chore

#47 release 1.0.28
  CHANGELOG.md
Labels: documentation

#55 doc: Add registeration part in plugin dev guides
  docs/en/guides/How-to-write-aggregator-plugins.md
  docs/en/guides/How-to-write-flusher-plugins.md
  docs/en/guides/How-to-write-input-plugins.md
  docs/en/guides/How-to-write-processor-plugins.md
  docs/zh/guides/How-to-write-aggregator-plugins.md
  docs/zh/guides/How-to-write-flusher-plugins.md
  docs/zh/guides/How-to-write-input-plugins.md
  docs/zh/guides/How-to-write-processor-plugins.md
  plugins/processor/json/README.md
Labels: documentation

#16 add processor_drop_last_key_test
  plugins/processor/droplastkey/processor_drop_last_key_test.go
Labels: enhancement

#15 add processor_base64_encoding_test
  plugins/processor/base64/encoding/processor_base64_encoding_test.go
Labels: enhancement

#14 add anchor_test
  plugins/processor/anchor/anchor_test.go
Labels: enhancement

#57 add processor md5 test
  plugins/processor/md5/processor_md5.go
  plugins/processor/md5/processor_md5_test.go
Labels: enhancement

#64 add release markdown scripts and doc
  CHANGELOG.md
  changes/v1.0.27.md
  changes/v1.0.28.md
  docs/en/guides/How-to-release.md
  docs/zh/guides/How-to-release.md
  scripts/generate-release-makedown.sh
Labels: documentation

#65 add doc for local deployment
  CHANGELOG.md
  README-cn.md
  docs/zh/usecases/How-to-local-deploy.md
  docs/zh/usecases/README.md
Labels: documentation

#67 Docs/how to setup
  docs/zh/usecases/How-to-local-deploy.md
  docs/zh/usecases/How-to-setup-in-k8s-environment.md
  docs/zh/usecases/How-to-setup-on-host.md
  docs/zh/usecases/README.md
Labels: documentation
