Repository alibaba/loongcollector, pull requests merged in 2021-11, with the labels that each got.

#1 polish docs
  README.md
  docs/en/guides/README.md
Labels: documentation

#2 add ilogtail ci process for static check
  .github/workflows/build-and-test.yaml
  .gitignore
  .golangci.yml
Labels: ci settings

#6 fix cgo build
  pkg/logtail/PluginAdapter.dll
  pkg/logtail/libPluginAdapter.so
  vendor/github.com/alibaba/ilogtail/pkg/logtail/PluginAdapter.dll
  vendor/github.com/alibaba/ilogtail/pkg/logtail/libPluginAdapter.so
Labels: chore

#5 keep sarama default setting ,use hash key for partition
  plugins/flusher/kafka/flusher_kafka.go
Labels: enhancement

#9 polish go modules from logtailplugin to ilogtail
  Makefile
  README-cn.md
  README.md
  docs/en/guides/How-to-use-logger.md
  docs/zh/guides/How-to-use-logger.md
  external/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner/go.mod
  helper/k8s_center.go.bak
  helper/k8s_shared_event_handler.go.bak
  pkg/protocol/proto/sls_logs.proto
  pkg/protocol/proto/sls_logs_transfer.proto
  plugins/input/skywalkingv2/code-gen.sh
  plugins/input/skywalkingv2/proto/common/CLR.proto
  plugins/input/skywalkingv2/proto/common/JVM.proto
  plugins/input/skywalkingv2/proto/common/common.proto
  plugins/input/skywalkingv2/proto/common/trace-common.proto
  plugins/input/skywalkingv2/proto/language-agent-v2/CLRMetric.proto
  plugins/input/skywalkingv2/proto/language-agent-v2/JVMMetric.proto
  plugins/input/skywalkingv2/proto/language-agent-v2/trace.proto
  plugins/input/skywalkingv2/proto/language-agent/ApplicationRegisterService.proto
  plugins/input/skywalkingv2/proto/language-agent/DiscoveryService.proto
  plugins/input/skywalkingv2/proto/language-agent/Downstream.proto
  plugins/input/skywalkingv2/proto/language-agent/JVMMetricsService.proto
  plugins/input/skywalkingv2/proto/language-agent/KeyWithIntegerValue.proto
  plugins/input/skywalkingv2/proto/language-agent/KeyWithStringValue.proto
  plugins/input/skywalkingv2/proto/language-agent/NetworkAddressRegisterService.proto
  plugins/input/skywalkingv2/proto/language-agent/TraceSegmentService.proto
  plugins/input/skywalkingv2/proto/register/InstancePing.proto
  plugins/input/skywalkingv2/proto/register/Register.proto
  plugins/input/skywalkingv3/proto-gen.sh
  plugins/input/skywalkingv3/proto/browser/BrowserPerf.proto
  plugins/input/skywalkingv3/proto/browser/BrowserPerfCompat.proto
  plugins/input/skywalkingv3/proto/common/Common.proto
  plugins/input/skywalkingv3/proto/event/Event.proto
  plugins/input/skywalkingv3/proto/language-agent/CLRMetric.proto
  plugins/input/skywalkingv3/proto/language-agent/CLRMetricCompat.proto
  plugins/input/skywalkingv3/proto/language-agent/ConfigurationDiscoveryService.proto
  plugins/input/skywalkingv3/proto/language-agent/JVMMetric.proto
  plugins/input/skywalkingv3/proto/language-agent/JVMMetricCompat.proto
  plugins/input/skywalkingv3/proto/language-agent/Meter.proto
  plugins/input/skywalkingv3/proto/language-agent/MeterCompat.proto
  plugins/input/skywalkingv3/proto/language-agent/Tracing.proto
  plugins/input/skywalkingv3/proto/language-agent/TracingCompat.proto
  plugins/input/skywalkingv3/proto/logging/Logging.proto
  plugins/input/skywalkingv3/proto/management/Management.proto
  plugins/input/skywalkingv3/proto/management/ManagementCompat.proto
  plugins/input/skywalkingv3/proto/profile/Profile.proto
  plugins/input/skywalkingv3/proto/profile/ProfileCompat.proto
  plugins/input/skywalkingv3/proto/service-mesh-probe/service-mesh-compat.proto
  plugins/input/skywalkingv3/proto/service-mesh-probe/service-mesh.proto
  plugins/input/skywalkingv3/trace_analyze.go.bak
  scripts/e2e.sh
  test/case/behavior/input_docker_stdout_multiline/Dockerfile
  test/case/behavior/input_docker_stdout_multiline/ilogtail-e2e.yaml
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner/go.mod
Labels: chore

#17 export docker mapping method
  helper/docker_center.go
Labels: chore

#18 export container collect fields
  plugins/input/docker/logmeta/metric_docker_file.go
  plugins/input/docker/rawstdout/input_docker_stdout.go
  plugins/input/docker/stdout/input_docker_stdout.go
Labels: chore

#22 service_http_server: unlink unix sock before listen
  CHANGELOG.md
  plugins/input/httpserver/input_http_server.go
  plugins/input/httpserver/input_http_server_test.go
Labels: bug

#19 Polish system metrics
  CHANGELOG.md
  plugins/input/systemv2/input_system_v2.go
Labels: enhancement

#20 fixed processor_regex not support regular expression
  CHANGELOG.md
  plugins/processor/regex/regex.go
  plugins/processor/regex/regex_benchmark_test.go
  plugins/processor/regex/regex_test.go
Labels: bug

#23 remove global variables in kubernetes meta to avoid data race
  CHANGELOG.md
  plugins/input/kubernetesmeta/input_kubernetes_meta.go
  plugins/input/kubernetesmeta/kubernetes_collect.go
  plugins/input/kubernetesmeta/kubernetes_collect_apps.go
  plugins/input/kubernetesmeta/kubernetes_collect_batch.go
  plugins/input/kubernetesmeta/kubernetes_collect_core.go
  plugins/input/kubernetesmeta/kubernetes_collect_networking.go
Labels: bug

#24 1.0.27 release
  CHANGELOG.md
Labels: documentation
