Repository alibaba/loongcollector, pull requests merged in 2022-07, with the labels that each got.

#177 fix cgo api bug
  CHANGELOG.md
  helper/container_discover_controller.go
  helper/container_export.go
  plugin_main/plugin_export.go
  pluginmanager/logstore_config.go
Labels: bug, core

#188 Opensource is not necessary to synchronize data with SLS
  .gitignore
  core/config_manager/ConfigManagerBase.cpp
  core/config_manager/ConfigManagerBase.h
  core/profile_sender/ProfileSender.cpp
  core/sender/Sender.h
Labels: bug

#186 add dns resolve when httping
  CHANGELOG.md
  plugins/input/netping/netping.go
Labels: bug

#193 add resource reference for k8s service
  CHANGELOG.md
  plugins/input/kubernetesmeta/input_kubernetes_meta.go
  plugins/input/kubernetesmeta/kubernetes_collect.go
Labels: enhancement

#178 Fix service register bug
  plugins/input/skywalkingv3/segment_analyze.go
  plugins/input/skywalkingv3/testdata/trace.json
  plugins/input/skywalkingv3/tracing_handle_test.go
Labels: bug

#206 chore: update fluster plugin doc format
  docs/en/guides/How-to-write-flusher-plugins.md
  docs/zh/guides/How-to-write-flusher-plugins.md
Labels: documentation
