Repository alibaba/loongcollector, pull requests merged in 2022-05, with the labels that each got.

#141 [fixed] fix so lib build by docker
  scripts/solib.sh
Labels: ci settings

#142 close #103, fix ut
  helper/docker_cri_adapter_test.go
Labels: bug

#139 add processor_fields_with_condition to support process actions after switch-case conditions …
  docs/en/plugins/plugin-list.md
  docs/en/plugins/processor/processor_fields_with_condition.md
  helper/envconfig/aliyun_log_config_define_others.go
  helper/envconfig/aliyun_log_config_define_others_test.go
  plugins/all/all.go
  plugins/input/hostmeta/input_host_meta_other.go
  plugins/input/process/input_process_cache_other.go
  plugins/input/process/input_process_other_test.go
  plugins/processor/fieldswithcondition/example.json
  plugins/processor/fieldswithcondition/processor_fields_with_condition.go
  plugins/processor/fieldswithcondition/processor_fields_with_condition_test.go
Labels: enhancement

#143 Support skywalking logging api
  plugins/aggregator/skywalking/aggregator_skywalking.go
  plugins/input/skywalkingv3/input_skywalking_agent_v3.go
  plugins/input/skywalkingv3/logging_handle.go
  plugins/input/skywalkingv3/logging_handle_test.go
  plugins/input/skywalkingv3/proto-gen.sh
  plugins/input/skywalkingv3/skywalking/network/logging/v3/Logging.pb.go
  plugins/input/skywalkingv3/skywalking/network/logging/v3/Logging_grpc.pb.go
  plugins/input/skywalkingv3/testdata/logging.json
Labels: enhancement

#146 Release 1.0.33
  changes/v1.0.33.md
Labels: documentation

#153 add-workload-for-kubernets-meta
  CHANGELOG.md
  plugins/input/kubernetesmeta/kubernetes_collect.go
  plugins/input/kubernetesmeta/kubernetes_collect_core.go
  plugins/input/kubernetesmeta/kubernetes_collect_core_test.go
Labels: enhancement

#152 fix cri update without sandbox bug
  CHANGELOG.md
  helper/docker_center.go
  helper/docker_cri_adapter.go
Labels: bug

#155 release v1.0.34
  CHANGELOG.md
  changes/v1.0.34.md
Labels: bug, enhancement

#157 add dns resolve time , add hostname to label, reduce MinIntervalSeconds
  CHANGELOG.md
  docs/en/plugins/metric_input/metric_input_netping.md
  plugins/input/netping/netping.go
  plugins/input/netping/netping_test.go
Labels: enhancement
