Repository alibaba/loongcollector, pull requests merged in 2022-12, with the labels that each got.

#544 doc: add dependency doc
  docs/cn/developer-guide/development-environment.md
  docs/cn/installation/sources/build.md
  docs/cn/installation/sources/dependencies.md
Labels: documentation

#551 fix: Incorrect dnsPolicy setting in ilogtail-daemonset.yaml
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/flusher/kafka.md
  docs/cn/data-pipeline/flusher/kafka_v2.md
  docs/cn/data-pipeline/input/input-docker-stdout.md
  docs/cn/getting-started/k8s-daemonset-to-kafka.md
  docs/cn/getting-started/k8slog-collect-to-sls.md
  docs/cn/installation/start-with-k8s.md
  example_config/start_with_k8s/ilogtail-daemonset.yaml
  k8s_templates/ilogtail-daemonset-file-to-kafka.yaml
  k8s_templates/ilogtail-daemonset-file-to-sls.yaml
  k8s_templates/ilogtail-daemonset-stdout-to-kafka.yaml
  k8s_templates/ilogtail-daemonset-stdout-to-sls.yaml
Labels: bug, documentation

#521 feat: add http flusher supporting influxdb protocol & add group aggregator supproting group logs by keys
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/aggregator/aggregator-content-value-group.md
  docs/cn/data-pipeline/flusher/http.md
  docs/cn/data-pipeline/input/service-http-service.md
  docs/cn/data-pipeline/overview.md
  docs/cn/developer-guide/log-protocol/README.md
  docs/cn/developer-guide/log-protocol/converter.md
  go.mod
  go.sum
  helper/converter_helper.go
  helper/decoder/common/comon.go
  helper/decoder/decoder.go
  helper/decoder/influxdb/decoder.go
  helper/decoder/prometheus/decoder.go
  helper/decoder/prometheus/decoder_test.go
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  licenses/LICENSE_OF_TESTENGINE_DEPENDENCIES.md
  pkg/go.mod
  pkg/go.sum
  pkg/protocol/converter/converter.go
  pkg/protocol/converter/converter_metric.go
  pkg/protocol/converter/converter_metric_test.go
  pkg/protocol/converter/influxdb_metric.go
  pkg/protocol/converter/influxdb_metric_test.go
  plugins/aggregator/contentvaluegroup/aggregator_content_value_group.go
  plugins/aggregator/contentvaluegroup/aggregator_content_value_group_test.go
  plugins/all/all.go
  plugins/flusher/http/flusher_http.go
  plugins/flusher/http/flusher_http_test.go
  plugins/input/httpserver/input_http_server.go
  plugins/input/httpserver/input_http_server_test.go
  test/case/behavior/flusher_http/docker-compose.yaml
  test/case/behavior/flusher_http/ilogtail-e2e.yaml
  test/case/behavior/input_httpserver/ilogtail-e2e.yaml
  test/config/config.go
  test/engine/boot/compose.go
  test/engine/controller/httpcase_control.go
  test/engine/controller/logtail_control.go
  test/engine/subscriber/influxdb.go
  test/engine/subscriber/influxdb_test.go
  test/engine/subscriber/subscriber.go
  test/go.mod
  test/go.sum
Labels: feature request

#566 fix ptr bug
  core/common/MachineInfoUtil.cpp
Labels: bug

#569 fix arm version compatibility
  plugin_main/wrapmemcpy/wrap_memcpy.go
  plugin_main/wrapmemcpy/wrap_memcpy.h
  plugin_main/wrapmemcpy/wrap_memcpy_others.go
  scripts/plugin_build.sh
  scripts/plugin_gocbuild.sh
Labels: bug
