Repository alibaba/loongcollector, pull requests merged in 2022-08, with the labels that each got.

#220 add support for multi-subscriber and yaml config
  .github/workflows/e2e-core.yaml
  .github/workflows/e2e.yaml
  .gitignore
  docs/cn/developer-guide/test/How-to-add-subscriber.md
  docs/cn/developer-guide/test/e2e-test.md
  test/README.md
  test/case/behavior/input_canal/ilogtail-e2e.yaml
  test/case/behavior/input_docker_event/ilogtail-e2e.yaml
  test/case/behavior/input_docker_rawstdout/ilogtail-e2e.yaml
  test/case/behavior/input_docker_rawstdout_multiline/ilogtail-e2e.yaml
  test/case/behavior/input_docker_static_file/ilogtail-e2e.yaml
  test/case/behavior/input_docker_stdout/ilogtail-e2e.yaml
  test/case/behavior/input_docker_stdout_multiline/ilogtail-e2e.yaml
  test/case/behavior/input_http/ilogtail-e2e.yaml
  test/case/behavior/input_mocklog/ilogtail-e2e.yaml
  test/case/behavior/input_mockmetric/ilogtail-e2e.yaml
  test/case/behavior/input_mysql/ilogtail-e2e.yaml
  test/case/behavior/input_nginx/ilogtail-e2e.yaml
  test/case/behavior/input_prometheus/ilogtail-e2e.yaml
  test/case/behavior/input_static_file/ilogtail-e2e.yaml
  test/case/core/alwaysonline_normal_config_exit_false/ilogtail-e2e.yaml
  test/case/core/alwaysonline_normal_config_resume/ilogtail-e2e.yaml
  test/case/core/block_holdon_resume/ilogtail-e2e.yaml
  test/case/core/load_same_block_config/ilogtail-e2e.yaml
  test/case/core/normal_holdon_resume/ilogtail-e2e.yaml
  test/case/core/recover_holdon_resume/ilogtail-e2e.yaml
  test/case/performance/mockpressure/ilogtail-e2e.yaml
  test/command.go
  test/config/config.go
  test/config/demo.go
  test/config/load.go
  test/engine/boot/compose.go
  test/engine/boot/compose_test.go
  test/engine/controller/boot_control.go
  test/engine/controller/logtail_control.go
  test/engine/controller/logtailplugin_control.go
  test/engine/controller/subscriber_control.go
  test/engine/controller/validator_control.go
  test/engine/subscriber/grpc.go
  test/engine/validator/sys_docker_profile.go
  test/engine/validator/sys_docker_profile_test.go
  test/example/ilogtail-e2e.yaml
  test/go.mod
  test/go.sum
  test/tools/generate.go
Labels: test

#294 Update docs related to compiling and development environment
  .devcontainer/devcontainer.json
  .gitignore
  README.md
  core/CMakeLists.txt
  docs/cn/README.md
  docs/cn/developer-guide/development-environment.md
  docs/cn/developer-guide/plugin-development/README.md
  docs/cn/installation/quick-start.md
  docs/cn/installation/sources/build.md
  docs/cn/installation/sources/docker-image.md
  docs/cn/installation/start-with-k8s.md
  example_config/README.md
  example_config/data_pipelines/file-delimiter.yaml
  example_config/data_pipelines/file-json.yaml
  example_config/data_pipelines/file_delimiter.yaml
  example_config/data_pipelines/multiline_java_stack_trace-split_log_regex.yaml
  example_config/data_pipelines/nginx-regex.yaml
  k8s_templates/README.md
  k8s_templates/ilogtail-daemonset-file-to-kafka.yaml
  k8s_templates/ilogtail-daemonset-file-to-sls.yaml
  k8s_templates/ilogtail-daemonset-stdout-to-kafka.yaml
  k8s_templates/ilogtail-daemonset-stdout-to-sls.yaml
  scripts/gen_build_scripts.sh
Labels: documentation

#302 [BUG] fix release scripts
  .devcontainer/devcontainer.json
  .gitignore
  scripts/gen_release_markdown.sh
  scripts/update_version.sh
Labels: bug

#303 release v1.1.1
  CHANGELOG.md
  Makefile
  changes/v1.1.1.md
  docker/Dockerfile_build
  docker/Dockerfile_development_part
  docker/Dockerfile_production
  docs/cn/developer-guide/publish-release.md
  docs/en/guides/How-to-build-with-docker.md
  docs/en/guides/How-to-do-manual-test.md
  docs/en/guides/How-to-release.md
  test/engine/boot/compose.go
Labels: documentation

#304 rm windows
  core/logtail_windows.cpp
Labels: enhancement

#310 remove unused declaration
  core/common/LogtailCommonFlags.h
Labels: enhancement

#316 change libebpf region
  docker/Dockerfile_development_part
Labels: enhancement, test

#318 glibc compatibility for kernel 2.x
  core/common/DynamicLibHelper.cpp
  core/common/DynamicLibHelper.h
  core/observer/metas/ConnectionMetaManager.cpp
  core/observer/network/NetworkObserver.cpp
  core/unittest/observer/NetLinkUnittest.cpp
  test/case/behavior/input_observer_http/mock/main.go
Labels: bug, core

#319 add glibc check
  .github/workflows/build.yaml
  core/CMakeLists.txt
  scripts/check_glibc.sh
  scripts/update_version.sh
Labels: test

#322 add dynamic libs to glibc check
  docs/cn/developer-guide/code-check/check-codestyle.md
  docs/cn/developer-guide/code-check/check-dependency-license.md
  docs/cn/developer-guide/code-check/check-license.md
  docs/cn/developer-guide/development-environment.md
  docs/cn/installation/sources/build.md
  scripts/check_glibc.sh
Labels: documentation, test

#330 [Doc] Add config example contributing doc
  docs/cn/SUMMARY.md
  docs/cn/contributing/CONTRIBUTING.md
  docs/cn/contributing/achievement.md
  docs/cn/contributing/developer.md
  example_config/README.md
  example_config/start_with_k8s/ilogtail-secret.yaml
  k8s_templates/README.md
Labels: documentation

#337 Update observer e2e
  .github/workflows/e2e.yaml
  test/case/behavior/input_observer_dns/ilogtail-e2e.yaml
  test/case/behavior/input_observer_http/ilogtail-e2e.yaml
Labels: test

#339 update observer doc
  docs/cn/data-pipeline/input/metric-observer.md
  docs/cn/data-pipeline/overview.md
Labels: documentation

#313 remove unnecessary chmod
  CHANGELOG.md
  core/checkpoint/CheckPointManager.cpp
  core/common/FileSystemUtil.cpp
  core/config_manager/ConfigManagerBase.cpp
  docs/cn/contributing/achievement.md
Labels: enhancement

#343 【BUG】fix ptr mismatch
  core/plugin/LogtailRuntimePlugin.cpp
Labels: bug
