Repository alibaba/loongcollector, pull requests merged in 2022-09, with the labels that each got.

#363 fix observer menu
  docs/cn/SUMMARY.md
Labels: documentation

#376 Refine Config Error Alarm
  core/plugin/LogtailPlugin.cpp
Labels: enhancement

#380 add-gpu-docs
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/input/service-gpu.md
  docs/cn/data-pipeline/overview.md
Labels: documentation

#347 polish libpcap
  core/observer/interface/network.h
  core/observer/metas/ServiceMetaCache.h
  core/observer/network/NetworkConfig.cpp
  core/observer/network/NetworkConfig.h
  core/observer/network/NetworkObserver.cpp
  core/observer/network/sources/pcap/PCAPWrapper.cpp
  core/observer/network/sources/pcap/PCAPWrapper.h
Labels: enhancement

#407 polish jmxfetch
  helper/docker_center.go
  helper/k8s.go
  helper/k8s_test.go
  plugins/input/jmxfetch/jmxfetch.go
  scripts/plugin_build.sh
Labels: enhancement

#412 Add sync_vendor script
  .gitignore
  Makefile
  external/sync_vendor.py
  scripts/sync_vendor.sh
  vendor/github.com/containerd/containerd/Makefile
  vendor/github.com/containerd/imgcrypt/Makefile
  vendor/github.com/containers/ocicrypt/Makefile
  vendor/github.com/fsouza/go-dockerclient/Makefile
  vendor/go.uber.org/zap/Makefile
  vendor/google.golang.org/grpc/Makefile
Labels: enhancement

#423 Polish jmxfetch
  plugins/input/jmxfetch/jmxfetch.go
  plugins/input/jmxfetch/jmxfetch_inner.go
  plugins/input/jmxfetch/manager.go
  plugins/input/jmxfetch/manager_test.go
Labels: enhancement

#427 fix container delete logic
  helper/container_discover_controller.go
  helper/docker_center.go
Labels: bug

#428 Add Roadmap
  docs/cn/README.md
Labels: documentation

#433 strip binaries to reduce dist size
  Makefile
  core/CMakeLists.txt
  core/aggregator/CMakeLists.txt
  core/app_config/CMakeLists.txt
  core/checkpoint/CMakeLists.txt
  core/common/CMakeLists.txt
  core/config/CMakeLists.txt
  core/config_manager/CMakeLists.txt
  core/controller/CMakeLists.txt
  core/event/CMakeLists.txt
  core/event_handler/CMakeLists.txt
  core/event_listener/CMakeLists.txt
  core/fuse/CMakeLists.txt
  core/helper/CMakeLists.txt
  core/log_pb/CMakeLists.txt
  core/logger/CMakeLists.txt
  core/monitor/CMakeLists.txt
  core/observer/CMakeLists.txt
  core/observer/network/CMakeLists.txt
  core/observer/network/protocols/CMakeLists.txt
  core/observer/network/protocols/dns/CMakeLists.txt
  core/observer/network/protocols/http/CMakeLists.txt
  core/observer/network/protocols/mysql/CMakeLists.txt
  core/observer/network/protocols/pgsql/CMakeLists.txt
  core/observer/network/protocols/redis/CMakeLists.txt
  core/parser/CMakeLists.txt
  core/plugin/CMakeLists.txt
  core/polling/CMakeLists.txt
  core/processor/CMakeLists.txt
  core/profile_sender/CMakeLists.txt
  core/profiler/CMakeLists.txt
  core/reader/CMakeLists.txt
  core/sdk/CMakeLists.txt
  core/sender/CMakeLists.txt
  core/shennong/CMakeLists.txt
  core/sls_control/CMakeLists.txt
  core/streamlog/CMakeLists.txt
  core/unittest/CMakeLists.txt
  core/unittest/app_config/CMakeLists.txt
  core/unittest/checkpoint/CMakeLists.txt
  core/unittest/common/CMakeLists.txt
  core/unittest/config/CMakeLists.txt
  core/unittest/config_sdk/CMakeLists.txt
  core/unittest/controller/CMakeLists.txt
  core/unittest/event/CMakeLists.txt
  core/unittest/event_handler/CMakeLists.txt
  core/unittest/log_pb/CMakeLists.txt
  core/unittest/logger/CMakeLists.txt
  core/unittest/observer/CMakeLists.txt
  core/unittest/parser/CMakeLists.txt
  core/unittest/polling/CMakeLists.txt
  core/unittest/processor/CMakeLists.txt
  core/unittest/profiler/CMakeLists.txt
  core/unittest/sdk/CMakeLists.txt
  core/unittest/sender/CMakeLists.txt
  scripts/dist.sh
  scripts/gen_build_scripts.sh
  upload_release_assets.sh
Labels: enhancement
