Repository alibaba/loongcollector, pull requests merged in 2022-06, with the labels that each got.

#148 Add telegraf monitor
  CHANGELOG.md
  helper/log_file_reader.go
  helper/service_helper.go
  pkg/util/alarm.go
  pluginmanager/self_telemetry_alarm.go
  plugins/input/docker/stdout/input_docker_stdout.go
  plugins/input/telegraf/input_telegraf.go
  plugins/input/telegraf/local_test/telegrafd
  plugins/input/telegraf/telegraf_log_collector.go
  plugins/input/telegraf/telegraf_log_collector_test.go
  plugins/input/telegraf/telegraf_log_file_processor.go
  plugins/input/telegraf/telegraf_manager.go
  plugins/input/telegraf/telegraf_manager_test.go
  vendor/github.com/alibaba/ilogtail/pkg/util/alarm.go
Labels: enhancement

#161 add err log for mysql collect
  .gitignore
  plugins/input/mysql/mysql.go
Labels: chore

#165 add http ping support
  CHANGELOG.md
  plugins/input/netping/netping.go
  plugins/input/netping/netping_test.go
Labels: enhancement

#168 add new cgo api called ProcessLogs
  CHANGELOG.md
  main/plugin_export.go
  pluginmanager/logstore_config.go
Labels: core

#140 enhance container export api
  CHANGELOG.md
  helper/container_discover_controller.go
  helper/container_export.go
  helper/docker_center.go
  helper/docker_center_file_discover_test.go
  helper/docker_center_test.go
  helper/docker_cri_adapter.go
  helper/docker_cri_adapter_others.go
  helper/envconfig/aliyun_log_config_define.go
  helper/envconfig/aliyun_log_config_define_test.go
  helper/envconfig/docker_env_config.go
  main/plugin_export.go
  plugins/flusher/sls/flusher_sls.go
  plugins/input/docker/event/input_docker_event.go
  plugins/input/docker/logmeta/metric_docker_file.go
  plugins/input/docker/rawstdout/input_docker_stdout.go
  plugins/input/docker/stdout/input_docker_stdout.go
  plugins/input/hostmeta/input_host_meta_linux.go
  plugins/input/journal/input_journal.go
  plugins/input/process/input_process_benchmark_test.go
  plugins/input/process/input_process_linux_test.go
Labels: enhancement, core

#181 Fix CI FAIL
  .github/workflows/e2e.yaml
  .github/workflows/static-check.yaml
  Makefile
  docker/Dockerfile_build
  scripts/docker_build.sh
  scripts/e2e.sh
  scripts/gen_build_scripts.sh
  test/case/behavior/input_docker_stdout_multiline/Dockerfile
  test/case/behavior/input_docker_stdout_multiline/ilogtail-e2e.yaml
  test/case/behavior/input_static_file/a.log
  test/command.go
  test/config/config.go
  test/config/demo.go
  test/engine/validator/sys_logtail_log_test.go
  test/example/ilogtail-e2e.yaml
Labels: ci settings, chore
