Repository alibaba/loongcollector, pull requests merged in 2022-02, with the labels that each got.

#92 update add_kubernets_meta
  docs/zh/performance/Performance-compare-with-filebeat.md
Labels: documentation

#94 release v1.0.30
  CHANGELOG.md
  changes/v1.0.30.md
Labels: documentation

#95 Implement ConfigurationDiscoveryService interface
  CHANGELOG.md
  plugins/input/skywalkingv3/configuration_discovery_handler.go
  plugins/input/skywalkingv3/input_skywalking_agent_v3.go
Labels: bug

#100 fix-process-raw-log-tag-sequence
  pluginmanager/logstore_config.go
  pluginmanager/logstore_config_test.go
  plugins/input/docker/stdout/docker_stdout_processor_test.go
Labels: bug

#102 convert download link to https
  scripts/generate-release-makedown.sh
Labels: chore

#106 add-telegraf-usecase-doc
  CHANGELOG.md
  README-cn.md
  docs/zh/usecases/How-to-use-telegraf-receiver.md
  docs/zh/usecases/README.md
Labels: documentation

#105 feat: processor_gotime supports unix timestamp formats.
  CHANGELOG.md
  docs/en/plugins/plugin-list.md
  docs/en/plugins/processor/processor_gotime.md
  plugins/processor/gotime/README.md
  plugins/processor/gotime/processor_gotime.go
  plugins/processor/gotime/processor_gotime_test.go
Labels: enhancement

#60 add content `_client_ip_` for syslog
  CHANGELOG.md
  README-cn.md
  README.md
  plugins/input/syslog/README.md
  plugins/input/syslog/syslog.go
  plugins/input/syslog/syslog_test.go
Labels: enhancement, plugin
