Repository alibaba/loongcollector, pull requests merged in 2022-01, with the labels that each got.

#68 update readme to add usecase
  CHANGELOG.md
  README-cn.md
  README.md
  docs/zh/usecases/How-to-setup-in-k8s-environment.md
Labels: documentation

#72 add processor_split_log_string process for kafka flusher deployment
  README-cn.md
  docs/zh/usecases/How-to-local-deploy-kafka-flusher.md
  docs/zh/usecases/README.md
Labels: documentation

#77 add filebeat compare doc
  README-cn.md
  docs/zh/README.md
  docs/zh/performance/Performance-compare-with-filebeat.md
  docs/zh/performance/README.md
Labels: documentation

#78 fix wrong matching lables for stdout input
  CHANGELOG.md
  docker/Dockerfile_whole
  plugins/input/docker/stdout/input_docker_stdout.go
Labels: bug

#79 Fix label matching
  .github/workflows/build.yaml
  .github/workflows/static-check.yaml
  docker/Dockerfile_whole
  plugins/input/docker/logmeta/metric_docker_file_test.go
  plugins/input/docker/stdout/input_docker_stdout.go
  plugins/input/docker/stdout/input_docker_stdout_test.go
  plugins/input/snmp/input_snmp.go
  plugins/input/snmp/input_snmp_test.go
Labels: bug

#81 v1.0.29 release
  CHANGELOG.md
  changes/v1.0.29.md
Labels: documentation

#83 change dingtalk group
  README-cn.md
  README.md
  docs/zh/performance/Performance-compare-with-filebeat.md
Labels: documentation

#86 polish process plugin for threadNum and fdNum
  CHANGELOG.md
  plugins/input/process/input_process.go
  plugins/input/process/input_process_cache_linux.go
Labels: bug

#85 Support prometheus multi instance
  CHANGELOG.md
  Makefile
  README.md
  docs/en/plugins/plugin-list.md
  docs/en/plugins/service_input/service_prometheus.md
  external/github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper_instance.go
  external/github.com/VictoriaMetrics/metrics/clear.go
  go.mod
  main/flags/flags.go
  main/plugin_export.go
  main/plugin_main.go
  pkg/logger/logger.go
  pluginmanager/plugin_manager.go
  plugins/flusher/stdout/flusher_stdout.go
  plugins/input/prometheus/input_prometheus.go
  test/case/behavior/input_prometheus/Dockerfile
  test/case/behavior/input_prometheus/docker-compose.yaml
  test/case/behavior/input_prometheus/exporter/go.mod
  test/case/behavior/input_prometheus/exporter/go.sum
  test/case/behavior/input_prometheus/exporter/main.go
  test/case/behavior/input_prometheus/ilogtail-e2e.yaml
  vendor/github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper_instance.go
  vendor/github.com/VictoriaMetrics/metrics/clear.go
  vendor/github.com/alibaba/ilogtail/pkg/logger/logger.go
Labels: enhancement

#88 add description for C and Go Part (#87)
  docs/zh/usecases/How-to-local-deploy-kafka-flusher.md
Labels: documentation
