Repository alibaba/loongcollector, pull requests merged in 2022-11, with the labels that each got.

#444 [Feature] inotify add deal with moveto event
  core/event_handler/EventHandler.cpp
  core/reader/LogFileReader.cpp
Labels: enhancement

#482 Polish ebpf l7 data structures
  CHANGELOG.md
  core/common/MachineInfoUtil.cpp
  core/observer/docs/schema.md
  core/observer/interface/global.cpp
  core/observer/interface/global.h
  core/observer/interface/helper.h
  core/observer/interface/layerfour.cpp
  core/observer/interface/type.h
  core/observer/metas/ContainerProcessGroup.cpp
  core/observer/metas/ContainerProcessGroup.h
  core/observer/network/NetworkConfig.cpp
  core/observer/network/NetworkConfig.h
  core/observer/network/NetworkObserver.cpp
  core/observer/network/NetworkObserver.h
  core/observer/network/protocols/ProtocolEventAggregators.cpp
  core/observer/network/protocols/ProtocolEventAggregators.h
  core/observer/network/protocols/category.h
  core/observer/network/protocols/common.h
  core/observer/network/protocols/dns/parser.cpp
  core/observer/network/protocols/dns/parser.h
  core/observer/network/protocols/dns/type.h
  core/observer/network/protocols/http/parser.cpp
  core/observer/network/protocols/http/parser.h
  core/observer/network/protocols/http/type.h
  core/observer/network/protocols/infer.h
  core/observer/network/protocols/mysql/parser.h
  core/observer/network/protocols/mysql/type.h
  core/observer/network/protocols/pgsql/parser.h
  core/observer/network/protocols/pgsql/type.h
  core/observer/network/protocols/redis/parser.h
  core/observer/network/protocols/redis/type.h
  core/observer/network/sources/ebpf/EBPFWrapper.cpp
  core/observer/network/sources/ebpf/EBPFWrapper.h
  core/unittest/observer/CGoupMetaUnittest.cpp
  core/unittest/observer/NetworkObserverUnittest.cpp
  core/unittest/observer/ObserverConfigUnittest.cpp
  core/unittest/observer/ProtocolDnsUnittest.cpp
  core/unittest/observer/ProtocolHttpUnittest.cpp
  core/unittest/observer/ProtocolMySqlUnittest.cpp
  core/unittest/observer/ProtocolPgsqlUnittest.cpp
  core/unittest/observer/ProtocolRedisUnittest.cpp
  core/unittest/observer/RawNetPacketReader.h
  core/unittest/reader/CMakeLists.txt
  docs/cn/data-pipeline/input/metric-observer.md
  helper/docker_center.go
  plugins/input/jmxfetch/jmxfetch.go
  plugins/input/jmxfetch/jmxfetchd.go
  plugins/input/jmxfetch/manager.go
  test/case/behavior/input_observer_dns/ilogtail-e2e.yaml
  test/case/behavior/input_observer_http/ilogtail-e2e.yaml
Labels: enhancement

#524 update VictoriaMetrics version to optimize Memory
  Makefile
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  plugins/input/prometheus/input_prometheus.go
Labels: enhancement

#525 processor desensitize
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/overview.md
  docs/cn/data-pipeline/processor/processor-desensitize.md
  plugins/all/all.go
  plugins/processor/desensitize/processor_desensitize.go
  plugins/processor/desensitize/processor_desensitize_test.go
Labels: feature request

#517 fix ip parsing problem given specific hostnames
  core/common/MachineInfoUtil.cpp
  core/common/MachineInfoUtil.h
  core/monitor/Monitor.cpp
  core/monitor/Monitor.h
  core/unittest/common/CMakeLists.txt
  core/unittest/common/MachineInfoUtilUnittest.cpp
Labels: feature request

#523 improve user agent info
  core/sls_control/SLSControl.cpp
  core/sls_control/SLSControl.h
Labels: feature request

#532 continue registering registered path during global path registration
  core/config_manager/ConfigManagerBase.cpp
Labels: bug

#536 remove deleted handlers during config update
  core/config_manager/ConfigManager.cpp
Labels: bug

#530 fix #529, fix docker fd leak and event lost
  CHANGELOG.md
  core/config_manager/ConfigManagerBase.cpp
  docs/cn/data-pipeline/flusher/sls.md
  go.mod
  go.sum
  helper/container_export.go
  helper/docker_center.go
  helper/docker_center_file_discover.go
  helper/docker_center_file_discover_test.go
  helper/docker_center_test.go
  helper/docker_cri_adapter.go
  helper/docker_cri_adapter_others.go
  helper/docker_cri_adapter_test.go
  helper/envconfig/aliyun_log_config_define_test.go
  helper/envconfig/docker_env_config.go
  helper/log_file_reader.go
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  licenses/LICENSE_OF_TESTENGINE_DEPENDENCIES.md
  pkg/logger/logger.go
  plugins/input/docker/event/input_docker_event.go
  plugins/input/docker/logmeta/metric_docker_file.go
  plugins/input/docker/rawstdout/input_docker_stdout.go
  plugins/input/docker/stdout/input_docker_stdout.go
  scripts/dependency_licenses.sh
  test/engine/boot/compose.go
  test/engine/validator/sys_docker_profile.go
  test/engine/validator/sys_docker_profile_test.go
  test/go.mod
  test/go.sum
Labels: bug
