Repository alibaba/loongcollector, pull requests merged in 2022-04, with the labels that each got.

#122 fix analyzeProductLog api call
  CHANGELOG.md
  external/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner/analyze_product_log.go
  helper/envconfig/product_api.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner/analyze_product_log.go
Labels: enhancement

#98 export contianer meta to C
  CHANGELOG.md
  main/plugin_export.go
Labels: enhancement

#126 [modify] add extra flags for prometheus scrape
  plugins/input/prometheus/input_prometheus.go
Labels: enhancement

#128 add docker build doc for image or dynamic lib
  CHANGELOG.md
  Makefile
  docker/Dockerfile_whole
  docs/en/guides/How-to-build-with-docker.md
  docs/en/guides/How-to-do-manual-test.md
  docs/en/guides/README.md
  docs/en/setup/README.md
  docs/zh/guides/How-to-build-with-docker.md
  docs/zh/guides/README.md
  docs/zh/setup/README.md
  scripts/docker-build.sh
  test/engine/boot/compose.go
Labels: documentation, ci settings

#134 support netping timeout, fix netping on windows
  CHANGELOG.md
  docs/en/plugins/metric_input/metric_input_netping.md
  plugins/input/netping/netping.go
  plugins/input/netping/netping_test.go
Labels: bug, enhancement

#135 limit netping timeout
  docs/en/plugins/metric_input/metric_input_netping.md
  plugins/input/netping/netping.go
Labels: enhancement
