Repository alibaba/loongcollector, pull requests merged in 2022-10, with the labels that each got.

#447 Enhance ebpf schema proposal
  core/observer/docs/schema.md
Labels: documentation, core

#461 add OS & Os version for low ebpf kernel support
  core/common/MachineInfoUtil.cpp
  core/common/MachineInfoUtil.h
  core/observer/network/sources/ebpf/EBPFWrapper.cpp
  core/observer/network/sources/ebpf/EBPFWrapper.h
Labels: enhancement

#470 fix jmxfetch bug
  plugins/input/jmxfetch/manager.go
  plugins/input/jmxfetch/manager_test.go
Labels: bug

#476 [DOC] update contributor
  docs/cn/contributing/achievement.md
  docs/cn/contributing/developer.md
Labels: documentation
