Repository alibaba/loongcollector, pull requests merged in 2023-03, with the labels that each got.

#694 compatible to windows compile
  core/app_config/AppConfig.cpp
Labels: core

#723 Polish ebpf e2e test
  scripts/e2e.sh
Labels: test

#711 Add async counter for unittest
  .devcontainer/Dockerfile
  helper/container_export_test.go
  helper/decoder/pyroscope/decoder.go
  helper/decoder/pyroscope/decoder_test.go
  helper/dumper.go
  helper/dumper_test.go
  helper/k8s.go
  helper/k8s_test.go
  helper/path_helper_test.go
  helper/platformmeta/aliyun_ecs.go
  helper/platformmeta/interface.go
  helper/platformmeta/mock.go
  helper/profile/meta.go
  helper/profile/meta_test.go
  helper/profile/pyroscope/jfr/jfr.go
  helper/profile/pyroscope/jfr/jfr_labels.proto
  helper/profile/pyroscope/jfr/jfr_test.go
  helper/profile/pyroscope/jfr/parser.go
  helper/profile/pyroscope/pprof/pprof.go
  helper/profile/pyroscope/pprof/pprof_test.go
  helper/profile/pyroscope/pprof/pyroscope.go
  helper/profile/pyroscope/raw/profile.go
  helper/slice_helper.go
  helper/slice_helper_test.go
  helper/split_log_helper.go
  helper/split_log_helper_test.go
  pkg/fmtstr/format_topic_test.go
  pkg/fmtstr/formatstring_test.go
  pkg/models/common_test.go
  pkg/models/logs.go
  plugins.yml
  plugins/aggregator/baseagg/aggregator_base_test.go
  plugins/flusher/opentelemetry/flusher_otlp_test.go
  plugins/input/jmxfetch/jmxfetch_log_file_processor_test.go
  plugins/processor/cloudmeta/cloud_meta.go
  plugins/processor/cloudmeta/cloud_meta_test.go
  plugins/test/async/count_helper.go
  test/engine/subscriber/influxdb.go
  test/engine/subscriber/influxdb_test.go
  tools/builder/testdata/external_plugins.yml
Labels: test

#741 add fork license markdown
  docs/cn/developer-guide/code-check/check-dependency-license.md
Labels: community

#685 feat: add loki flusher
  .github/workflows/e2e.yaml
  CHANGELOG.md
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/flusher/loki.md
  docs/cn/data-pipeline/overview.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  licenses/LICENSE_OF_TESTENGINE_DEPENDENCIES.md
  pkg/protocol/converter/converter.go
  plugins.yml
  plugins/flusher/loki/flusher_loki.go
  test/case/behavior/flusher_loki/Dockerfile
  test/case/behavior/flusher_loki/docker-compose.yaml
  test/case/behavior/flusher_loki/ilogtail-e2e.yaml
  test/case/behavior/flusher_loki/loki-config.yaml
  test/engine/subscriber/loki.go
  test/go.mod
  test/go.sum
Labels: feature request
