Repository alibaba/loongcollector, pull requests merged in 2023-12, with the labels that each got.

#1255 fix: Correct parsing errors in ProcessorParseApsaraNative with large buffer input
  core/common/JsonUtil.cpp
  core/config/Config.h
  core/processor/ProcessorParseApsaraNative.cpp
  core/processor/ProcessorParseApsaraNative.h
  core/unittest/processor/ProcessorDesensitizeNativeUnittest.cpp
  core/unittest/processor/ProcessorFilterNativeUnittest.cpp
  core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
  core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
Labels: bug

#1272 When REGEX_LOG is set, mTimeKey will be set to "time".
  core/config_manager/ConfigManagerBase.cpp
Labels: bug

#1280 Fix issue where container IP is occasionally empty for Kubernetes pods in HostNetwork mode
  pkg/helper/docker_center.go
Labels: bug

#1282 Upgrade environment variable logic using new Pipeline API for logtail environment configuration management
  CHANGELOG.md
  go.mod
  go.sum
  helper/envconfig/aliyun_ecs_meta_data.go
  helper/envconfig/aliyun_log_config_define.go
  helper/envconfig/aliyun_log_config_define_others.go
  helper/envconfig/aliyun_log_config_define_others_test.go
  helper/envconfig/aliyun_log_config_define_test.go
  helper/envconfig/aliyun_log_config_define_windows.go
  helper/envconfig/aliyun_log_config_define_windows_test.go
  helper/envconfig/aliyunlog_client.go
  helper/envconfig/aliyunlog_operation_wrapper.go
  helper/envconfig/custom_error.go
  helper/envconfig/docker_env_config_manager.go
  helper/envconfig/docker_env_config_manager_test.go
  helper/envconfig/product_api.go
  helper/envconfig/product_logtail_config.go
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  pkg/helper/container_export.go
  pkg/helper/docker_center.go
  pkg/helper/env_tags.go
  pkg/helper/eventrecorder/event_define.go
  pkg/helper/eventrecorder/event_recorder.go
  scripts/dependency_licenses.sh
Labels: feature request

#1289 Fix delimiter parsing for logs with leading spaces
  core/parser/DelimiterModeFsmParser.cpp
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
Labels: bug

#1288 [backport]Fix delimiter parsing for logs with leading spaces
  core/parser/DelimiterModeFsmParser.cpp
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
Labels: bug

#1293 Fix timezone handling in native processors
  core/processor/ProcessorParseApsaraNative.cpp
  core/processor/ProcessorParseTimestampNative.cpp
Labels: bug

#1291 fix: reset checkpoint dump time after dir registration completes to avoid log duplication
  core/file_server/FileServer.cpp
Labels: bug

#1285 Fix timestamp parsing compatibility issue for apsara log
  core/processor/ProcessorParseApsaraNative.cpp
  core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
Labels: bug

#1281 Improve goprofile plugin to support real local IP inclusion
  pkg/util/net_helper.go
  plugins/input/goprofile/discovery_static.go
Labels: enhancement

#1286 [backport]fix: resolve crash by setting CURLOPT_NOSIGNAL for thread safety
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  config_server/service/Dockerfile
  core/common/CrashBackTraceUtil.cpp
  core/common/MachineInfoUtil.cpp
  core/monitor/Monitor.cpp
  core/sdk/CurlAsynInstance.cpp
  core/sender/Sender.cpp
  core/sls_control/SLSControl.cpp
  core/unittest/processor/LogFilterUnittest.cpp
  core/unittest/processor/ProcessorDesensitizeNativeUnittest.cpp
  docker/Dockerfile_build
  docker/Dockerfile_development_part
  docker/Dockerfile_goc
  docs/cn/developer-guide/development-environment.md
  docs/cn/installation/sources/dependencies.md
Labels: bug

#1284 fix: Prevent crash due to concurrent map access in Go plugin log processing
  pluginmanager/plugin_runner_v1.go
Labels: bug

#1301 [backport] fix: reset checkpoint dump time after dir registration completes to avoid log duplication
  core/controller/EventDispatcherBase.cpp
Labels: bug
