Repository alibaba/loongcollector, pull requests merged in 2023-05, with the labels that each got.

#825 Fix: stale env config
  CHANGELOG.md
  helper/envconfig/aliyun_log_config_define.go
Labels: bug

#835 fix system disk total val
  CHANGELOG.md
  plugins/input/systemv2/input_system_v2.go
Labels: bug

#841 fix: processor_gotime empty time zone
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/overview.md
  docs/cn/data-pipeline/processor/processor-gotime.md
  docs/en/plugins/processor/processor_gotime.md
  plugins/processor/gotime/processor_gotime.go
  plugins/processor/gotime/processor_gotime_test.go
Labels: bug

#844 fix env config cache
  helper/envconfig/docker_env_config_manager.go
Labels: bug

#840 add tags to profile log
  core/controller/EventDispatcherBase.cpp
  core/event_handler/EventHandler.cpp
  core/processor/LogProcess.cpp
  core/profiler/LogFileProfiler.cpp
  core/profiler/LogFileProfiler.h
Labels: enhancement

#827 otlp decoder for metrics(v1)
  CHANGELOG.md
  docs/cn/data-pipeline/input/service-http-server.md
  docs/cn/data-pipeline/input/service-otlp.md
  pkg/protocol/decoder/opentelemetry/decoder.go
  pkg/protocol/decoder/opentelemetry/decoder_test.go
  pkg/protocol/decoder/opentelemetry/otlpDataToPielineGroupEvents.go
  pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go
  plugins/input/opentelemetry/receiver.go
  plugins/input/opentelemetry/service_oltp.go
  plugins/input/opentelemetry/service_otlp_test.go
  plugins/input/opentelemetry/service_otlp_v1_test.go
Labels: feature request

#856 fix: should throw err on applyPluginConfig error
  pluginmanager/logstore_config.go
Labels: bug

#824 feat: upgrade kafka sarama client
  CHANGELOG.md
  docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
  docs/cn/data-pipeline/input/service-kafka.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  plugins/flusher/kafkav2/authentication.go
  plugins/flusher/kafkav2/flusher_kafka_v2.go
  plugins/input/kafka/input_kafka.go
  plugins/input/kafka/input_kafka_test.go
Labels: enhancement

#873 close #872, fix container file fd not close if multiple configs monitor the same dir
  core/event_handler/EventHandler.cpp
Labels: bug

#878 kubernetes add support kruise
  CHANGELOG.md
  docs/cn/data-pipeline/input/metric-kubernetes-meta.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  plugins/input/goprofile/discovery_kubernetes.go
  plugins/input/goprofile/discovery_static.go
  plugins/input/goprofile/golang_profile.go
  plugins/input/goprofile/manager.go
  plugins/input/kubernetesmeta/crd_open_kruise.go
  plugins/input/kubernetesmeta/input_kubernetes_meta.go
  test/case/behavior/flusher_loki/Dockerfile
  test/case/behavior/flusher_loki/loki-config.yaml
Labels: enhancement
