Repository alibaba/loongcollector, pull requests merged in 2023-02, with the labels that each got.

#603 feat: flusher pulsar
  CHANGELOG.md
  Makefile
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/flusher/pulsar.md
  docs/cn/data-pipeline/overview.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  pkg/fmtstr/formatstring_test.go
  plugins/all/all.go
  plugins/flusher/pulsar/authentication.go
  plugins/flusher/pulsar/flusher_pulsar.go
  plugins/flusher/pulsar/producers.go
  test/go.mod
  test/go.sum
Labels: feature request

#622 fix blocking problem caused by alwaysonline config update
  CHANGELOG.md
  core/controller/EventDispatcherBase.cpp
  core/processor/LogProcess.cpp
  pluginmanager/logstore_config.go
Labels: bug

#580 feat: add clickhouse flusher (#554)
  CHANGELOG.md
  docs/cn/SUMMARY.md
  docs/cn/data-pipeline/flusher/clickhouse.md
  docs/cn/data-pipeline/overview.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  licenses/LICENSE_OF_TESTENGINE_DEPENDENCIES.md
  plugins/all/all.go
  plugins/flusher/clickhouse/authentication.go
  plugins/flusher/clickhouse/flusher_clickhouse.go
  plugins/flusher/clickhouse/flusher_clickhouse_test.go
  test/case/behavior/flusher_clickhouse/docker-compose.yaml
  test/case/behavior/flusher_clickhouse/ilogtail-e2e.yaml
  test/engine/subscriber/clickhouse.go
  test/go.mod
  test/go.sum
Labels: feature request

#654 Fix metadata aggregator
  docs/cn/data-pipeline/aggregator/aggregator-metadata-group.md
  plugins/aggregator/metadatagroup/aggregator_metadata_group.go
  plugins/aggregator/metadatagroup/aggregator_metadata_group_test.go
Labels: bug

#662 fix #661, fix update time to make container removable
  CHANGELOG.md
  helper/docker_center.go
Labels: bug

#684 enhance prometheus support staleness
  CHANGELOG.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  plugins.yml
  plugins/input/prometheus/input_prometheus.go
Labels: enhancement
