Repository alibaba/loongcollector, pull requests merged in 2023-09, with the labels that each got.

#1101 fix: fix filename mismatch for empty file inode reuse
  CHANGELOG.md
  core/logtail.cpp
  core/logtail_windows.cpp
  core/reader/LogFileReader.cpp
Labels: bug

#1109 fix: fix checkpoint reopen stopped container file
  CHANGELOG.md
  core/checkpoint/CheckPointManager.cpp
  core/checkpoint/CheckPointManager.h
  core/controller/EventDispatcherBase.cpp
  core/event_handler/EventHandler.cpp
  core/reader/LogFileReader.cpp
  plugins/input/mockd/input_mockd.go
Labels: bug

#1130 add otel metric parser processor
  CHANGELOG.md
  docs/cn/data-pipeline/processor/processor-otel-metric.md
  pkg/protocol/decoder/opentelemetry/otlp_metric_parser.go
  plugins/processor/otel/processor_otel_metric.go
  plugins/processor/otel/processor_otel_metric_test.go
Labels: feature request

#1152 clear_time_ns only when successLogSize < logGroup.logs_size and logPtr != NULL
  core/processor/LogProcess.cpp
Labels: bug

#1060 Unify metrics format
  core/common/LogtailCommonFlags.cpp
  core/common/LogtailCommonFlags.h
  core/logtail.cpp
  core/logtail_windows.cpp
  core/plugin/LogtailPlugin.cpp
  pkg/config/global_config.go
  pkg/helper/log_helper.go
  pkg/helper/log_helper_test.go
  pkg/helper/metrics_helper.go
  pkg/protocol/decoder/influxdb/decoder.go
  pkg/protocol/decoder/influxdb/decoder_test.go
  pkg/protocol/decoder/prometheus/decoder.go
  pkg/protocol/decoder/statsd/decoder.go
  plugins/input/example/metric_checkpoint_example.go
  plugins/input/example/metric_example.go
  plugins/input/httpserver/input_http_server.go
  plugins/input/mock/input_mock.go
  plugins/input/netping/netping.go
  plugins/input/netping/netping_test.go
  plugins/input/process/input_process.go
  plugins/input/process/input_process_cache.go
  plugins/input/process/input_process_cache_linux.go
  plugins/input/process/input_process_cache_other.go
  plugins/input/process/input_process_test.go
  plugins/input/prometheus/sls_writer.go
  plugins/input/skywalkingv2/jvm_metric_handle.go
  plugins/input/skywalkingv3/clr_metric_handle.go
  plugins/input/skywalkingv3/jvm_metric_handle.go
  plugins/input/skywalkingv3/jvm_metric_handle_test.go
  plugins/input/skywalkingv3/meter_handle.go
  plugins/input/skywalkingv3/testdata/clr_metrics.json
  plugins/input/skywalkingv3/testdata/jvm_metrics.json
  plugins/input/skywalkingv3/testdata/meter_histogram.json
  plugins/input/skywalkingv3/testdata/meter_singlevalue.json
  plugins/input/systemv2/input_system_linux.go
  plugins/input/systemv2/input_system_others.go
  plugins/input/systemv2/input_system_v2.go
  plugins/processor/appender/processor_appender.go
Labels: enhancement
