Repository alibaba/loongcollector, pull requests merged in 2023-04, with the labels that each got.

#785 doc: fix example error of ext_groupinfo_filter
  docs/cn/data-pipeline/extension/ext-groupinfo-filter.md
Labels: documentation

#790 add support for proxy through env
  core/app_config/AppConfigBase.cpp
  core/app_config/AppConfigBase.h
  core/common/EnvUtil.cpp
  core/common/EnvUtil.h
  core/common/StringTools.h
  core/sdk/Common.cpp
  core/sdk/Common.h
  core/sdk/CurlImp.cpp
  core/unittest/app_config/AppConfigUnittest.cpp
  pkg/go.mod
  pkg/go.sum
Labels: feature request

#707 add switch policy for sls data server endpoint
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  core/common/util.cpp
  core/common/util.h
  core/config_manager/ConfigManagerBase.cpp
  core/config_manager/ConfigManagerBase.h
  core/sdk/Client.h
  core/sender/Sender.cpp
  core/sender/Sender.h
Labels: feature request

#807 ping add local mode support
  plugins/input/netping/netping.go
Labels: enhancement
