Repository alibaba/loongcollector, pull requests merged in 2024-09, with the labels that each got.

#1734 use zstd compression for profile info
  core/go_pipeline/LogtailPlugin.cpp
  core/profile_sender/ProfileSender.cpp
Labels: enhancement

#1733 [backport] use zstd compression for profile info
  core/go_pipeline/LogtailPlugin.cpp
Labels: enhancement

#1732 add util function for supporting cgroup in enterprise version
  core/application/Application.cpp
  core/common/FileSystemUtil.cpp
  core/common/FileSystemUtil.h
  core/monitor/Monitor.cpp
  core/monitor/Monitor.h
Labels: feature request

#1739 remove fuse and LogtailInsight
  core/CMakeLists.txt
  core/checkpoint/AdhocCheckpointManager.cpp
  core/common/HashUtil.cpp
  core/common/HashUtil.h
  core/common/LogFileOperator.cpp
  core/common/LogFileOperator.h
  core/file_server/EventDispatcher.cpp
  core/file_server/event_handler/EventHandler.cpp
  core/file_server/reader/LogFileReader.cpp
  core/fuse/FuseFileBlacklist.h
  core/fuse/UlogfsHandler.h
  core/fuse/ulogfslib_file.h
  core/fuse/ulogfslib_file_dummy.cpp
  core/helper/CMakeLists.txt
  core/helper/LogtailInsight.cpp
  core/helper/LogtailInsight.h
Labels: miscellaneous

#1747 fix ut build failure casued by fuse removal
  core/file_server/reader/LogFileReader.cpp
  core/unittest/common/LogFileOperatorUnittest.cpp
Labels: bug

#1759 Fixed an issue where the pipeline would get stuck during configuration changes.
  core/go_pipeline/LogtailPlugin.cpp
Labels: bug

#1756 add metric for queue
  core/file_server/reader/LogFileReader.cpp
  core/monitor/LogtailMetric.cpp
  core/monitor/LogtailMetric.h
  core/monitor/LoongCollectorMetricTypes.h
  core/monitor/MetricConstants.cpp
  core/monitor/MetricConstants.h
  core/pipeline/Pipeline.cpp
  core/pipeline/plugin/instance/FlusherInstance.cpp
  core/pipeline/plugin/interface/Flusher.h
  core/pipeline/queue/BoundedProcessQueue.cpp
  core/pipeline/queue/BoundedProcessQueue.h
  core/pipeline/queue/BoundedQueueInterface.h
  core/pipeline/queue/BoundedSenderQueueInterface.cpp
  core/pipeline/queue/BoundedSenderQueueInterface.h
  core/pipeline/queue/CircularProcessQueue.cpp
  core/pipeline/queue/CircularProcessQueue.h
  core/pipeline/queue/ExactlyOnceQueueManager.cpp
  core/pipeline/queue/ExactlyOnceQueueManager.h
  core/pipeline/queue/ExactlyOnceSenderQueue.cpp
  core/pipeline/queue/ExactlyOnceSenderQueue.h
  core/pipeline/queue/ProcessQueueInterface.cpp
  core/pipeline/queue/ProcessQueueInterface.h
  core/pipeline/queue/ProcessQueueItem.h
  core/pipeline/queue/ProcessQueueManager.cpp
  core/pipeline/queue/ProcessQueueManager.h
  core/pipeline/queue/QueueInterface.h
  core/pipeline/queue/SenderQueue.cpp
  core/pipeline/queue/SenderQueue.h
  core/pipeline/queue/SenderQueueItem.h
  core/pipeline/queue/SenderQueueManager.cpp
  core/pipeline/queue/SenderQueueManager.h
  core/plugin/flusher/blackhole/FlusherBlackHole.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/runner/FlusherRunner.cpp
  core/unittest/event_handler/ModifyHandlerUnittest.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
  core/unittest/plugin/PluginMock.h
  core/unittest/queue/BoundedProcessQueueUnittest.cpp
  core/unittest/queue/CircularProcessQueueUnittest.cpp
  core/unittest/queue/ExactlyOnceQueueManagerUnittest.cpp
  core/unittest/queue/ExactlyOnceSenderQueueUnittest.cpp
  core/unittest/queue/ProcessQueueManagerUnittest.cpp
  core/unittest/queue/SenderQueueManagerUnittest.cpp
  core/unittest/queue/SenderQueueUnittest.cpp
  core/unittest/reader/ForceReadUnittest.cpp
  core/unittest/sender/FlusherRunnerUnittest.cpp
Labels: core

#1781 fix: do not use gtid if gtid is disabled
  plugins/input/canal/input_canal.go
Labels: bug

#1731 Flusher supports new metricstore endpoint, which optimizes time series data storage and query
  CHANGELOG.md
  core/plugin/flusher/sls/DiskBufferWriter.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/plugin/flusher/sls/FlusherSLS.h
  core/protobuf/sls/logtail_buffer_meta.proto
  core/protobuf/sls/sls_logs.proto
  core/sdk/Client.cpp
  core/sdk/Client.h
  core/sdk/Common.cpp
  core/sdk/Common.h
  core/sdk/CurlImp.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
Labels: core
