Repository alibaba/loongcollector, pull requests merged in 2024-05, with the labels that each got.

#1472 improve worst case performance when all events failed to process (#1465)
  core/application/Application.cpp
  core/processor/ProcessorFilterNative.cpp
  core/processor/ProcessorParseApsaraNative.cpp
  core/processor/ProcessorParseDelimiterNative.cpp
  core/processor/ProcessorParseJsonNative.cpp
  core/processor/ProcessorParseRegexNative.cpp
  core/processor/ProcessorParseTimestampNative.cpp
  core/processor/ProcessorSPL.cpp
  core/processor/ProcessorSplitMultilineLogStringNative.cpp
  core/unittest/models/CMakeLists.txt
  core/unittest/models/EventGroupBenchmark.cpp
Labels: enhancement

#1474 ensure ssl is linked after spl to fix compilation errors
  core/config_manager/CMakeLists.txt
  core/dependencies.cmake
  core/sdk/CMakeLists.txt
  core/unittest/CMakeLists.txt
Labels: bug

#1480 fix all compile waring in main program
  core/common/BoostRegexValidator.cpp
  core/common/Lock.h
  core/observer/metas/ConnectionMetaManager.cpp
  core/pipeline/PipelineManager.cpp
  core/processor/ProcessorSPL.cpp
  core/sdk/Common.cpp
  core/unittest/CMakeLists.txt
Labels: miscellaneous

#1486 allow empty endpoint in enterprise flusher_sls to avoid unsuccessful config load
  core/flusher/FlusherSLS.cpp
Labels: bug

#1484 implement metric event
  core/models/MetricEvent.cpp
  core/models/MetricEvent.h
  core/models/MetricValue.cpp
  core/models/MetricValue.h
  core/models/PipelineEvent.h
  core/unittest/models/CMakeLists.txt
  core/unittest/models/MetricEventUnittest.cpp
  core/unittest/models/MetricValueUnittest.cpp
  core/unittest/processor/ProcessorMergeMultilineLogNativeUnittest.cpp
Labels: core, feature request

#1488 implement span event
  core/models/SpanEvent.cpp
  core/models/SpanEvent.h
  core/unittest/models/CMakeLists.txt
  core/unittest/models/SpanEventUnittest.cpp
Labels: core, feature request

#1496 Fix Go Plugin nanosecond
  pkg/helper/local_collector.go
  pkg/helper/local_context.go
  pkg/helper/log_helper.go
  pkg/pipeline/context.go
  pkg/protocol/converter/converter.go
  pkg/protocol/converter/converter_single_log_flatten_test.go
  pkg/protocol/converter/converter_test.go
  pkg/protocol/converter/custom_single_log_test.go
  pkg/protocol/converter/influxdb_metric_test.go
  pkg/protocol/converter/jsonline_test.go
  pkg/protocol/converter/otlp.go
  pkg/protocol/converter/otlp_test.go
  pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go
  pluginmanager/context_imp.go
  pluginmanager/metric_wrapper.go
  pluginmanager/plugin_runner_v1.go
  pluginmanager/service_wrapper.go
  plugins/flusher/clickhouse/flusher_clickhouse.go
  plugins/flusher/elasticsearch/flusher_elasticsearch.go
  plugins/flusher/http/flusher_http.go
  plugins/flusher/http/flusher_http_test.go
  plugins/flusher/kafkav2/flusher_kafka_v2.go
  plugins/flusher/loki/flusher_loki.go
  plugins/flusher/opentelemetry/flusher_otlp.go
  plugins/flusher/opentelemetry/flusher_otlp_test.go
  plugins/flusher/pulsar/flusher_pulsar.go
  plugins/input/docker/stdout/docker_stdout_processor.go
  plugins/input/skywalkingv3/ot_trace.go
  plugins/processor/gotime/processor_gotime.go
  plugins/processor/split/logregex/split_log_regex.go
  plugins/processor/split/logstring/split_log_string.go
  plugins/processor/strptime/strptime.go
  plugins/test/common.go
  plugins/test/mock/context.go
Labels: bug

#1500 fix zero nbytes when read log
  core/reader/LogFileReader.cpp
  core/unittest/reader/CMakeLists.txt
  core/unittest/reader/LogFileReaderUnittest.cpp
  core/unittest/reader/RemoveLastIncompleteLogUnittest.cpp
Labels: bug

#1495 fix go input duplicated collection due to unexpected go checkpoint deletion
  pluginmanager/checkpoint_manager.go
  pluginmanager/checkpoint_manager_test.go
Labels: bug

#1505 fix go checkpoint deletion problem caused by always online config mistaken for deleted
  pluginmanager/always_online_manager.go
  pluginmanager/always_online_manager_test.go
  pluginmanager/logstore_config.go
  pluginmanager/plugin_manager.go
Labels: bug

#1506 add timeout warning
  core/reader/LogFileReader.cpp
Labels: enhancement

#1507 Prevent circular dependency crash in YAML parsing (to #1503)
  core/common/YamlUtil.cpp
  core/common/YamlUtil.h
  core/unittest/common/YamlUtilUnittest.cpp
Labels: bug
