Repository alibaba/loongcollector, pull requests merged in 2024-08, with the labels that each got.

#1656 Support MetricEvent serialize to logGroup
  core/common/TimeUtil.cpp
  core/common/TimeUtil.h
  core/serializer/SLSSerializer.cpp
  core/unittest/serializer/SLSSerializerUnittest.cpp
Labels: enhancement

#1518 improve Android compatibility
  core/common/RuntimeUtil.cpp
  core/common/links.cmake
  core/dependencies.cmake
  core/logtail.cpp
Labels: enhancement

#1655 support flusher route for pipeline event group
  core/CMakeLists.txt
  core/config/PipelineConfig.cpp
  core/config/PipelineConfig.h
  core/pipeline/Pipeline.cpp
  core/pipeline/Pipeline.h
  core/route/Condition.cpp
  core/route/Condition.h
  core/route/Router.cpp
  core/route/Router.h
  core/unittest/CMakeLists.txt
  core/unittest/config/CMakeLists.txt
  core/unittest/config/PipelineConfigUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/route/CMakeLists.txt
  core/unittest/route/ConditionUnittest.cpp
  core/unittest/route/RouterUnittest.cpp
  docs/cn/plugins/flusher/flusher-sls.md
  docs/cn/plugins/flusher/router.md
Labels: core, feature request

#1664 fix processor delimiter parse double quote
  core/parser/DelimiterModeFsmParser.cpp
  core/parser/DelimiterModeFsmParser.h
  core/processor/ProcessorParseDelimiterNative.cpp
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
  tools/coverage-diff/main.py
Labels: bug

#1659 separate feedbackqueue into three distinct interfaces
  core/application/Application.cpp
  core/checkpoint/RangeCheckpoint.h
  core/event/BlockEventManager.h
  core/pipeline/Pipeline.cpp
  core/pipeline/PipelineContext.h
  core/plugin/instance/FlusherInstance.h
  core/plugin/interface/Flusher.h
  core/processor/daemon/LogProcess.h
  core/queue/BoundedProcessQueue.cpp
  core/queue/BoundedProcessQueue.h
  core/queue/BoundedQueueInterface.h
  core/queue/BoundedSenderQueueInterface.cpp
  core/queue/BoundedSenderQueueInterface.h
  core/queue/ExactlyOnceQueueManager.cpp
  core/queue/ExactlyOnceQueueManager.h
  core/queue/ExactlyOnceSenderQueue.cpp
  core/queue/ExactlyOnceSenderQueue.h
  core/queue/ProcessQueueInterface.cpp
  core/queue/ProcessQueueInterface.h
  core/queue/ProcessQueueManager.cpp
  core/queue/ProcessQueueManager.h
  core/queue/QueueInterface.h
  core/queue/QueueKey.h
  core/queue/QueueKeyManager.h
  core/queue/SenderQueue.h
  core/queue/SenderQueueItem.h
  core/reader/LogFileReader.h
  core/unittest/event_handler/ModifyHandlerUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/queue/BoundedProcessQueueUnittest.cpp
  core/unittest/queue/CMakeLists.txt
  core/unittest/queue/ExactlyOnceSenderQueueUnittest.cpp
  core/unittest/queue/FeedbackInterfaceMock.h
  core/unittest/queue/ProcessQueueManagerUnittest.cpp
  core/unittest/reader/ForceReadUnittest.cpp
Labels: core

#1669 [backport] fix processor delimiter parse double quote (#1664)
  core/parser/DelimiterModeFsmParser.cpp
  core/parser/DelimiterModeFsmParser.h
  core/processor/ProcessorParseDelimiterNative.cpp
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
Labels: bug

#1672 [backport 1.8] Add processor_gotime with nanosecond to other time format conversion capability
  plugins/processor/gotime/processor_gotime.go
  plugins/processor/gotime/processor_gotime_test.go
Labels: enhancement

#1630 Add k8s meta module to support k8s meta plugin and k8s meta http server.
  docs/cn/plugins/input/service-kubernetesmeta-v2.md
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  licenses/LICENSE_OF_TESTENGINE_DEPENDENCIES.md
  pkg/go.mod
  pkg/go.sum
  pkg/helper/k8smeta/k8s_meta_cache_pod.go
  pkg/helper/k8smeta/k8s_meta_cache_pod_test.go
  pkg/helper/k8smeta/k8s_meta_cache_service.go
  pkg/helper/k8smeta/k8s_meta_const.go
  pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
  pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache_test.go
  pkg/helper/k8smeta/k8s_meta_http_server.go
  pkg/helper/k8smeta/k8s_meta_manager.go
  pkg/helper/k8smeta/k8s_meta_store_interface.go
  pkg/helper/k8smeta/label_matcher.go
  pkg/util/util.go
  plugin_main/flags/flags.go
  plugin_main/plugin_export.go
  plugin_main/plugin_main.go
  plugins.yml
  plugins/input/kubernetesmetav1/README.md
  plugins/input/kubernetesmetav1/crd_open_kruise.go
  plugins/input/kubernetesmetav1/input_kubernetes_meta.go
  plugins/input/kubernetesmetav1/input_kubernetes_meta_test.go
  plugins/input/kubernetesmetav1/kubernetes_collect.go
  plugins/input/kubernetesmetav1/kubernetes_collect_apps.go
  plugins/input/kubernetesmetav1/kubernetes_collect_batch.go
  plugins/input/kubernetesmetav1/kubernetes_collect_core.go
  plugins/input/kubernetesmetav1/kubernetes_collect_core_test.go
  plugins/input/kubernetesmetav1/kubernetes_collect_networking.go
  plugins/input/kubernetesmetav1/kubernetes_collect_storage.go
  plugins/input/kubernetesmetav2/meta_collector.go
  plugins/input/kubernetesmetav2/meta_collector_const.go
  plugins/input/kubernetesmetav2/meta_collector_pod.go
  plugins/input/kubernetesmetav2/meta_collector_pod_test.go
  plugins/input/kubernetesmetav2/meta_collector_service.go
  plugins/input/kubernetesmetav2/meta_collector_service_test.go
  plugins/input/kubernetesmetav2/service_meta.go
  test/go.mod
  test/go.sum
Labels: feature request

#1704 feat: add ext_default_encoder with prometheus encoder
  docs/cn/SUMMARY.md
  docs/cn/plugins/extension/README.md
  docs/cn/plugins/extension/ext-default-encoder.md
  docs/cn/plugins/overview.md
  go.mod
  pkg/go.mod
  pkg/go.sum
  pkg/pipeline/extensions/encoder.go
  pkg/protocol/encoder/common/common.go
  pkg/protocol/encoder/encoder.go
  pkg/protocol/encoder/prometheus/encoder_prometheus.go
  pkg/protocol/encoder/prometheus/encoder_prometheus_test.go
  pkg/protocol/encoder/prometheus/utils.go
  pkg/protocol/encoder/prometheus/utils_test.go
  plugins.yml
  plugins/extension/default_encoder/default_encoder.go
  plugins/extension/default_encoder/default_encoder_test.go
Labels: enhancement
