Repository alibaba/loongcollector, pull requests merged in 2024-11, with the labels that each got.

#1845 support custom protobuf serializer for logGroup to improve send performance
  .github/workflows/build-core-ut.yaml
  core/CMakeLists.txt
  core/pipeline/Pipeline.cpp
  core/pipeline/serializer/SLSSerializer.cpp
  core/plugin/flusher/sls/FlusherSLS.h
  core/protobuf/sls/LogGroupSerializer.cpp
  core/protobuf/sls/LogGroupSerializer.h
  core/protobuf/sls/RawLog.cpp
  core/protobuf/sls/RawLog.h
  core/protobuf/sls/RawLogGroup.cpp
  core/protobuf/sls/RawLogGroup.h
  core/unittest/log_pb/CMakeLists.txt
  core/unittest/log_pb/LogGroupSerializerUnittest.cpp
  core/unittest/log_pb/PBUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/serializer/SLSSerializerUnittest.cpp
  docker/Dockerfile_coverage
  docs/cn/developer-guide/test/unit-test.md
Labels: enhancement, core

#1841 HTTP Trigger && Count Logs
  test/engine/steps.go
  test/engine/trigger/protocol.go
Labels: enhancement

#1853 Fix alarm send fail
  core/monitor/LogtailAlarm.cpp
Labels: bug

#1851 fix: convert chinese log path on windows
  core/file_server/reader/LogFileReader.cpp
  core/file_server/reader/LogFileReader.h
  core/runner/ProcessorRunner.cpp
Labels: bug

#1859 fix: use-after-free when remove pipeline but not clear flusher pointer
  core/pipeline/Pipeline.cpp
Labels: bug

#1844 test: add rand sleep ut
  core/unittest/prometheus/TargetSubscriberSchedulerUnittest.cpp
Labels: test

#1840 optimize: 1. reserve metric events before parse log events, 2. use SetTagNoCopy in Relabel, 3. optimize the logic of delete labels which starts with "__"
  core/plugin/processor/inner/ProcessorPromParseMetricNative.cpp
  core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
  core/plugin/processor/inner/ProcessorPromRelabelMetricNative.h
  core/prometheus/labels/Relabel.cpp
  core/prometheus/labels/Relabel.h
  core/prometheus/schedulers/TargetSubscriberScheduler.cpp
  core/unittest/processor/ProcessorPromRelabelMetricNativeUnittest.cpp
  core/unittest/prometheus/RelabelUnittest.cpp
Labels: enhancement

#1850 do not separate event group when group size excceeds min batch size to improve performance
  core/models/EventPool.cpp
  core/models/PipelineEventGroup.cpp
  core/monitor/metric_constants/ComponentMetrics.cpp
  core/monitor/metric_constants/MetricConstants.h
  core/pipeline/batch/BatchItem.h
  core/pipeline/batch/BatchedEvents.cpp
  core/pipeline/batch/Batcher.h
  core/pipeline/batch/FlushStrategy.h
  core/pipeline/queue/BoundedProcessQueue.cpp
  core/pipeline/queue/CircularProcessQueue.cpp
  core/pipeline/queue/ProcessQueueInterface.cpp
  core/pipeline/queue/ProcessQueueInterface.h
  core/pipeline/queue/SenderQueue.cpp
  core/pipeline/queue/SenderQueue.h
  core/pipeline/serializer/SLSSerializer.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/plugin/flusher/sls/FlusherSLS.h
  core/runner/FlusherRunner.cpp
  core/runner/FlusherRunner.h
  core/runner/ProcessorRunner.cpp
  core/runner/sink/http/HttpSink.cpp
  core/unittest/batch/BatchItemUnittest.cpp
  core/unittest/batch/BatcherUnittest.cpp
  core/unittest/batch/FlushStrategyUnittest.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
  core/unittest/instance_config/InstanceConfigManagerUnittest.cpp
Labels: enhancement

#1863 read blocked event as soon as process queue triggers feedback to improve file reading performance
  core/file_server/event/BlockEventManager.cpp
  core/file_server/event_handler/LogInput.cpp
  core/file_server/event_handler/LogInput.h
Labels: enhancement

#1873 Changed the endpoint source type from `LOCAL` to `REMOTE` in the `Init` method of `FlusherSLS`.
  core/application/Application.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
Labels: miscellaneous

#1856 add raw event type
  core/models/EventPool.cpp
  core/models/EventPool.h
  core/models/PipelineEvent.cpp
  core/models/PipelineEvent.h
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/models/PipelineEventPtr.h
  core/models/RawEvent.cpp
  core/models/RawEvent.h
  core/pipeline/Pipeline.cpp
  core/pipeline/PipelineContext.h
  core/pipeline/batch/BatchedEvents.cpp
  core/pipeline/serializer/SLSSerializer.cpp
  core/plugin/input/InputFile.cpp
  core/plugin/processor/inner/ProcessorSplitLogStringNative.cpp
  core/plugin/processor/inner/ProcessorSplitLogStringNative.h
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.h
  core/unittest/input/InputFileUnittest.cpp
  core/unittest/models/CMakeLists.txt
  core/unittest/models/EventPoolUnittest.cpp
  core/unittest/models/PipelineEventGroupUnittest.cpp
  core/unittest/models/PipelineEventPtrUnittest.cpp
  core/unittest/models/PipelineEventUnittest.cpp
  core/unittest/models/RawEventUnittest.cpp
  core/unittest/processor/ProcessorSplitLogStringNativeUnittest.cpp
  core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
  core/unittest/serializer/SLSSerializerUnittest.cpp
Labels: core, feature request

#1887 [backport 2.1] fix PreservedDirDepth not working with polling and wildcard path
  core/checkpoint/CheckPointManager.cpp
  core/checkpoint/CheckPointManager.h
  core/config/provider/CommonConfigProvider.cpp
  core/config_manager/ConfigManager.cpp
  core/config_manager/ConfigManager.h
  core/controller/EventDispatcher.cpp
  core/dependencies.cmake
  core/event_handler/EventHandler.cpp
  core/event_handler/LogInput.cpp
  core/file_server/FileDiscoveryOptions.cpp
  core/file_server/FileServer.cpp
  core/monitor/LogtailAlarm.cpp
  core/monitor/LogtailAlarm.h
  core/monitor/Monitor.cpp
  core/polling/PollingCache.h
  core/polling/PollingDirFile.cpp
  core/polling/PollingDirFile.h
  core/polling/PollingModify.cpp
  core/polling/PollingModify.h
  core/unittest/CMakeLists.txt
  core/unittest/polling/CMakeLists.txt
  core/unittest/polling/PollingPreservedDirDepthUnittest.cpp
Labels: bug

#1923 fix core caused by failed queue push
  core/runner/ProcessorRunner.cpp
Labels: bug
