Repository alibaba/loongcollector, pull requests merged in 2024-10, with the labels that each got.

#1820 [backport] remove use_containerd to keep compatibility
  pkg/helper/container_discover_controller.go
Labels: bug

#1812 Fix the checkContainerType out-of-bounds memory issue
  core/reader/LogFileReader.cpp
Labels: bug

#1816 fix: set instance after target_relabel, use address if not exist, update retry cnt in scrape scheduler
  core/prometheus/schedulers/ScrapeScheduler.cpp
  core/prometheus/schedulers/TargetSubscriberScheduler.cpp
Labels: bug

#1821 fix: prom runner register block main thread when network error
  core/prometheus/PrometheusInputRunner.cpp
  core/prometheus/PrometheusInputRunner.h
Labels: bug

#1822 fix: asyn curl runner(and http sink) forget to update runningHandlers when network error
  core/common/http/AsynCurlRunner.cpp
  core/common/http/AsynCurlRunner.h
  core/runner/sink/http/HttpSink.cpp
  core/runner/sink/http/HttpSink.h
Labels: bug

#1823 fix: support reentrant AsynCurlRunner and Timer
  core/common/http/AsynCurlRunner.cpp
  core/common/timer/Timer.cpp
Labels: enhancement

#1826 fix: set tag not delete tag in honor relabel
  core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
  core/unittest/processor/ProcessorPromRelabelMetricNativeUnittest.cpp
Labels: bug

#1807 Optimize metrics reporting
  core/application/Application.cpp
  core/common/compression/Compressor.cpp
  core/common/compression/Compressor.h
  core/common/compression/CompressorFactory.cpp
  core/file_server/FileServer.cpp
  core/file_server/event_handler/LogInput.cpp
  core/file_server/event_handler/LogInput.h
  core/file_server/polling/PollingDirFile.cpp
  core/file_server/polling/PollingDirFile.h
  core/monitor/LogFileProfiler.cpp
  core/monitor/LogFileProfiler.h
  core/monitor/LogtailMetric.cpp
  core/monitor/LogtailMetric.h
  core/monitor/LoongCollectorMetricTypes.h
  core/monitor/MetricExportor.cpp
  core/monitor/MetricExportor.h
  core/monitor/Monitor.cpp
  core/monitor/Monitor.h
  core/monitor/metric_constants/AgentMetrics.cpp
  core/monitor/metric_constants/ComponentMetrics.cpp
  core/monitor/metric_constants/MetricConstants.h
  core/monitor/metric_constants/PipelineMetrics.cpp
  core/monitor/metric_constants/PluginMetrics.cpp
  core/monitor/metric_constants/RunnerMetrics.cpp
  core/pipeline/Pipeline.cpp
  core/pipeline/Pipeline.h
  core/pipeline/batch/Batcher.h
  core/pipeline/plugin/instance/ProcessorInstance.cpp
  core/pipeline/plugin/instance/ProcessorInstance.h
  core/pipeline/plugin/interface/Plugin.h
  core/pipeline/queue/BoundedProcessQueue.cpp
  core/pipeline/queue/CircularProcessQueue.cpp
  core/pipeline/queue/QueueInterface.h
  core/pipeline/queue/SenderQueue.cpp
  core/pipeline/route/Router.cpp
  core/pipeline/serializer/SLSSerializer.cpp
  core/pipeline/serializer/Serializer.h
  core/prometheus/PrometheusInputRunner.cpp
  core/runner/FlusherRunner.cpp
  core/runner/FlusherRunner.h
  core/runner/ProcessorRunner.cpp
  core/runner/sink/http/HttpSink.cpp
  core/unittest/batch/BatcherUnittest.cpp
  core/unittest/compression/CompressorFactoryUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/queue/BoundedProcessQueueUnittest.cpp
  core/unittest/queue/CircularProcessQueueUnittest.cpp
  core/unittest/queue/SenderQueueUnittest.cpp
  core/unittest/route/RouterUnittest.cpp
  pkg/helper/k8smeta/k8s_meta_manager.go
  pkg/helper/self_metrics_agent_constants.go
  pkg/helper/self_metrics_plugin_constants.go
  pkg/helper/self_metrics_runner_constants.go
  plugin_main/plugin_export.go
  pluginmanager/logstore_config.go
  pluginmanager/logstore_config_test.go
  pluginmanager/plugin_manager.go
  pluginmanager/plugin_wrapper.go
  pluginmanager/self_telemetry_statistics.go
Labels: enhancement

#1824 fix: remove deprecated profile in ProcessorRunner
  core/runner/ProcessorRunner.cpp
Labels: bug

#1825 fix deadlock on LogInput and Processor Runner thread
  core/file_server/event/BlockEventManager.cpp
  core/file_server/event/BlockEventManager.h
  core/file_server/event_handler/LogInput.cpp
  core/unittest/event/BlockedEventManagerUnittest.cpp
  core/unittest/event/CMakeLists.txt
  core/unittest/reader/ForceReadUnittest.cpp
Labels: bug

#1827 support discarding route tag if needed
  core/pipeline/Pipeline.cpp
  core/pipeline/route/Condition.cpp
  core/pipeline/route/Condition.h
  core/pipeline/route/Router.cpp
  core/pipeline/route/Router.h
  core/unittest/route/ConditionUnittest.cpp
  core/unittest/route/RouterUnittest.cpp
Labels: enhancement

#1803 Update chinese doc link
  README.md
Labels: documentation

#1835 feat: Enhance configuration handling, send crash alarms only after appconfig initialization and refactor SLS client manager
  .github/workflows/build-core-ut.yaml
  .gitignore
  config_server/protocol/v2/agentV2.proto
  core/app_config/AppConfig.cpp
  core/app_config/AppConfig.h
  core/application/Application.cpp
  core/common/Constants.cpp
  core/common/Constants.h
  core/config/PipelineConfig.cpp
  core/config/common_provider/CommonConfigProvider.h
  core/config/provider/ConfigProvider.cpp
  core/config/watcher/InstanceConfigWatcher.cpp
  core/dependencies.cmake
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/plugin/flusher/sls/SLSClientManager.cpp
  core/plugin/flusher/sls/SLSClientManager.h
  core/protobuf/config_server/v1/agent.pb.cc
  core/protobuf/config_server/v1/agent.pb.h
  core/protobuf/config_server/v2/agent.pb.cc
  core/protobuf/config_server/v2/agent.pb.h
  core/unittest/sender/SenderUnittest.cpp
  docker/Dockerfile_coverage
Labels: enhancement

#1832 improve send log and adjust runner exit timeout
  core/CMakeLists.txt
  core/application/Application.cpp
  core/checkpoint/RangeCheckpoint.h
  core/common/http/AsynCurlRunner.cpp
  core/common/http/Curl.cpp
  core/common/http/HttpRequest.h
  core/config/InstanceConfigManager.cpp
  core/config/InstanceConfigManager.h
  core/config/common_provider/CommonConfigProvider.cpp
  core/deps/README.md
  core/deps/build.sh
  core/models/PipelineEventGroup.h
  core/monitor/Monitor.cpp
  core/monitor/metric_constants/MetricConstants.h
  core/monitor/metric_constants/PipelineMetrics.cpp
  core/monitor/metric_constants/PluginMetrics.cpp
  core/pipeline/Pipeline.cpp
  core/pipeline/Pipeline.h
  core/pipeline/PipelineManager.cpp
  core/pipeline/plugin/instance/FlusherInstance.cpp
  core/pipeline/plugin/instance/FlusherInstance.h
  core/pipeline/queue/ExactlyOnceQueueManager.cpp
  core/pipeline/queue/ExactlyOnceQueueManager.h
  core/pipeline/queue/ProcessQueueManager.cpp
  core/pipeline/queue/ProcessQueueManager.h
  core/pipeline/queue/SenderQueueItem.h
  core/plugin/flusher/sls/DiskBufferWriter.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/plugin/flusher/sls/SLSClientManager.cpp
  core/plugin/processor/inner/ProcessorSplitLogStringNative.cpp
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
  core/runner/FlusherRunner.cpp
  core/runner/FlusherRunner.h
  core/runner/ProcessorRunner.cpp
  core/runner/sink/http/HttpSink.cpp
  core/unittest/config/CommonConfigProviderUnittest.cpp
  core/unittest/instance_config/InstanceConfigManagerUnittest.cpp
  core/unittest/models/PipelineEventGroupUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
Labels: enhancement

#1799 Implemented self-monitoring logic for eBPF-related plugins
  core/ebpf/SelfMonitor.cpp
  core/ebpf/SelfMonitor.h
  core/ebpf/SourceManager.cpp
  core/ebpf/SourceManager.h
  core/ebpf/eBPFServer.cpp
  core/ebpf/eBPFServer.h
  core/ebpf/handler/AbstractHandler.h
  core/ebpf/handler/ObserveHandler.cpp
  core/ebpf/include/export.h
  core/monitor/metric_constants/MetricConstants.h
  core/monitor/metric_constants/PluginMetrics.cpp
  core/monitor/metric_constants/RunnerMetrics.cpp
  core/plugin/input/InputFileSecurity.cpp
  core/plugin/input/InputFileSecurity.h
  core/plugin/input/InputNetworkObserver.cpp
  core/plugin/input/InputNetworkObserver.h
  core/plugin/input/InputNetworkSecurity.cpp
  core/plugin/input/InputNetworkSecurity.h
  core/plugin/input/InputProcessSecurity.cpp
  core/plugin/input/InputProcessSecurity.h
  core/unittest/ebpf/eBPFServerUnittest.cpp
  core/unittest/input/InputFileSecurityUnittest.cpp
  core/unittest/input/InputNetworkObserverUnittest.cpp
  core/unittest/input/InputNetworkSecurityUnittest.cpp
  core/unittest/input/InputProcessSecurityUnittest.cpp
Labels: enhancement

#1817 support event pool
  core/app_config/AppConfig.h
  core/common/LogstoreFeedbackQueue.h
  core/config/InstanceConfig.h
  core/models/EventPool.cpp
  core/models/EventPool.h
  core/models/LogEvent.cpp
  core/models/LogEvent.h
  core/models/MetricEvent.cpp
  core/models/MetricEvent.h
  core/models/PipelineEvent.cpp
  core/models/PipelineEvent.h
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/models/PipelineEventPtr.h
  core/models/SpanEvent.cpp
  core/models/SpanEvent.h
  core/monitor/metric_constants/ComponentMetrics.cpp
  core/monitor/metric_constants/MetricConstants.h
  core/monitor/metric_constants/PluginMetrics.cpp
  core/pipeline/batch/BatchedEvents.cpp
  core/pipeline/batch/BatchedEvents.h
  core/pipeline/batch/Batcher.h
  core/pipeline/queue/BoundedSenderQueueInterface.h
  core/pipeline/queue/ExactlyOnceSenderQueue.cpp
  core/pipeline/queue/ExactlyOnceSenderQueue.h
  core/pipeline/queue/SenderQueue.cpp
  core/pipeline/queue/SenderQueue.h
  core/plugin/processor/inner/ProcessorPromParseMetricNative.cpp
  core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
  core/plugin/processor/inner/ProcessorSplitLogStringNative.cpp
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
  core/prometheus/labels/TextParser.cpp
  core/runner/ProcessorRunner.cpp
  core/runner/ProcessorRunner.h
  core/runner/sink/http/HttpSink.cpp
  core/runner/sink/http/HttpSink.h
  core/spl/PipelineEventGroupOutput.cpp
  core/unittest/batch/BatchStatusUnittest.cpp
  core/unittest/batch/BatchedEventsUnittest.cpp
  core/unittest/batch/CMakeLists.txt
  core/unittest/batch/FlushStrategyUnittest.cpp
  core/unittest/event/BlockedEventManagerUnittest.cpp
  core/unittest/models/CMakeLists.txt
  core/unittest/models/EventPoolUnittest.cpp
  core/unittest/models/LogEventUnittest.cpp
  core/unittest/models/MetricEventUnittest.cpp
  core/unittest/models/PipelineEventGroupUnittest.cpp
  core/unittest/models/PipelineEventPtrUnittest.cpp
  core/unittest/models/SpanEventUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/processor/ProcessorParseTimestampNativeUnittest.cpp
  core/unittest/provider/ProviderUnittest.cpp
  core/unittest/queue/ExactlyOnceQueueManagerUnittest.cpp
  core/unittest/queue/ExactlyOnceSenderQueueUnittest.cpp
  core/unittest/queue/SenderQueueUnittest.cpp
Labels: core, feature request

#1838 support custom http response body and body data write callback
  core/common/common.cmake
  core/common/http/AsynCurlRunner.cpp
  core/common/http/Curl.cpp
  core/common/http/HttpRequest.cpp
  core/common/http/HttpRequest.h
  core/common/http/HttpResponse.cpp
  core/common/http/HttpResponse.h
  core/metadata/K8sMetadata.cpp
  core/plugin/flusher/sls/SLSResponse.cpp
  core/prometheus/async/PromFuture.cpp
  core/prometheus/async/PromHttpRequest.cpp
  core/prometheus/async/PromHttpRequest.h
  core/prometheus/schedulers/BaseScheduler.h
  core/prometheus/schedulers/ScrapeScheduler.cpp
  core/prometheus/schedulers/ScrapeScheduler.h
  core/prometheus/schedulers/TargetSubscriberScheduler.cpp
  core/prometheus/schedulers/TargetSubscriberScheduler.h
  core/runner/sink/http/HttpSink.cpp
  core/runner/sink/http/HttpSinkRequest.h
  core/unittest/common/http/CurlUnittest.cpp
  core/unittest/common/timer/HttpRequestTimerEventUnittest.cpp
  core/unittest/prometheus/PromAsynUnittest.cpp
  core/unittest/prometheus/ScrapeSchedulerUnittest.cpp
  core/unittest/prometheus/TargetSubscriberSchedulerUnittest.cpp
Labels: enhancement

#1828 tag_standardization
  core/CMakeLists.txt
  core/config/common_provider/CommonConfigProvider.cpp
  core/constants/Constants.cpp
  core/constants/Constants.h
  core/constants/TagConstants.cpp
  core/constants/TagConstants.h
  core/file_server/ConfigManager.cpp
  core/file_server/reader/LogFileReader.cpp
  core/models/PipelineEventGroup.h
  core/monitor/LogFileProfiler.cpp
  core/monitor/LogtailAlarm.cpp
  core/monitor/Monitor.cpp
  core/plugin/processor/CommonParserOptions.cpp
  core/plugin/processor/ProcessorDesensitizeNative.cpp
  core/plugin/processor/inner/ProcessorSplitLogStringNative.h
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
  core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.h
  core/unittest/config/ConfigUpdatorUnittest.cpp
  core/unittest/processor/ProcessorMergeMultilineLogNativeUnittest.cpp
  core/unittest/processor/ProcessorParseContainerLogNativeUnittest.cpp
  core/unittest/processor/ProcessorSplitLogStringNativeUnittest.cpp
  core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
  core/unittest/processor/ProcessorTagNativeUnittest.cpp
  core/unittest/reader/ForceReadUnittest.cpp
  core/unittest/sender/SenderUnittest.cpp
Labels: enhancement

#1839 feat: add metric check methods for e2e engine
  test/engine/steps.go
  test/engine/verify/count.go
Labels: test
