Repository alibaba/loongcollector, pull requests merged in 2024-07, with the labels that each got.

#1533 export k8s metadata through http server
  plugins/input/kubernetesmeta/client.go
  plugins/input/kubernetesmeta/input_kubernetes_meta.go
  plugins/input/kubernetesmeta/kubernetes_http_server.go
Labels: feature request

#1559 Improve C++ core compilation time
  core/CMakeLists.txt
  core/app_config/CMakeLists.txt
  core/application/CMakeLists.txt
  core/batch/CMakeLists.txt
  core/common/CMakeLists.txt
  core/common/common.cmake
  core/common/links.cmake
  core/compression/CMakeLists.txt
  core/config/CMakeLists.txt
  core/config/provider/CMakeLists.txt
  core/config/watcher/CMakeLists.txt
  core/config_manager/CMakeLists.txt
  core/config_server_pb/CMakeLists.txt
  core/controller/CMakeLists.txt
  core/dependencies.cmake
  core/event/CMakeLists.txt
  core/event_handler/CMakeLists.txt
  core/event_listener/CMakeLists.txt
  core/file_server/CMakeLists.txt
  core/flusher/CMakeLists.txt
  core/flusher/flusher.cmake
  core/flusher/links.cmake
  core/fuse/CMakeLists.txt
  core/go_pipeline/CMakeLists.txt
  core/input/CMakeLists.txt
  core/input/input.cmake
  core/input/links.cmake
  core/links.cmake
  core/log_pb/CMakeLists.txt
  core/logger/CMakeLists.txt
  core/models/CMakeLists.txt
  core/monitor/CMakeLists.txt
  core/observer/CMakeLists.txt
  core/observer/network/CMakeLists.txt
  core/observer/network/protocols/CMakeLists.txt
  core/observer/network/protocols/dns/CMakeLists.txt
  core/observer/network/protocols/http/CMakeLists.txt
  core/observer/network/protocols/mysql/CMakeLists.txt
  core/observer/network/protocols/redis/CMakeLists.txt
  core/parser/CMakeLists.txt
  core/pipeline/CMakeLists.txt
  core/plugin/CMakeLists.txt
  core/plugin/creator/CMakeLists.txt
  core/plugin/instance/CMakeLists.txt
  core/plugin/interface/CMakeLists.txt
  core/processor/CMakeLists.txt
  core/processor/daemon/CMakeLists.txt
  core/processor/inner/CMakeLists.txt
  core/processor/links.cmake
  core/processor/processor.cmake
  core/profile_sender/CMakeLists.txt
  core/queue/CMakeLists.txt
  core/reader/CMakeLists.txt
  core/sdk/CMakeLists.txt
  core/sender/CMakeLists.txt
  core/serializer/CMakeLists.txt
  core/sls_control/CMakeLists.txt
  core/spl/CMakeLists.txt
  core/unittest/CMakeLists.txt
Labels: enhancement

#1596 [backport] fix: JSON truncation caused by escaped zero byte (#1594)
  config_server/service/Dockerfile
  core/processor/ProcessorParseJsonNative.cpp
  core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
  docker/Dockerfile.centos7-cve-fix
  docker/Dockerfile_production
Labels: bug

#1595 [backport] fix: JSON truncation caused by escaped zero byte (#1594)
  config_server/service/Dockerfile
  core/processor/ProcessorParseJsonNative.cpp
  core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
  docker/Dockerfile.centos7-cve-fix
  docker/Dockerfile_production
Labels: bug

#1611 fix core caused by concurrent use of non-thread-safe gethostbyname
  core/common/MachineInfoUtil.cpp
Labels: bug

#1620 recover readers exactly from checkpoint
  core/checkpoint/CheckPointManager.h
  core/event_handler/EventHandler.cpp
  core/event_handler/EventHandler.h
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
  core/unittest/event_handler/CMakeLists.txt
  core/unittest/event_handler/ModifyHandlerUnittest.cpp
Labels: bug

#1637 fix checkpoint dump idx in reader array
  core/checkpoint/CheckPointManager.cpp
  core/checkpoint/CheckPointManager.h
  core/event_handler/EventHandler.cpp
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
Labels: bug

#1638 [backport] fix checkpoint dump idx in reader array
  core/checkpoint/CheckPointManager.cpp
  core/checkpoint/CheckPointManager.h
  core/event_handler/EventHandler.cpp
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
Labels: bug

#1615 fix: input_kafka consumer wont close due to ctx never done.
  plugins/input/kafka/input_kafka.go
Labels: bug

#1614 Feat: prometheus relabel lib
  core/prometheus/Labels.cpp
  core/prometheus/Labels.h
  core/prometheus/Relabel.cpp
  core/prometheus/Relabel.h
  core/unittest/prometheus/CMakeLists.txt
  core/unittest/prometheus/LabelsUnittest.cpp
  core/unittest/prometheus/RelabelUnittest.cpp
Labels: feature request

#1644 fix: GTID Truncation Issue and Improve Consistency in Checkpoint Management
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  pkg/helper/self_metrics_v2_imp.go
  pkg/helper/self_metrics_v2_imp_test.go
  pkg/helper/self_metrics_vector_imp.go
  pkg/helper/self_metrics_vector_imp_test.go
  pkg/pipeline/self_metrics.go
  plugins/input/canal/input_canal.go
Labels: bug

#1647 [backport 1.8] fix: GTID Truncation Issue and Improve Consistency in Checkpoint Management
  .github/workflows/build-pure-plugin.yaml
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  pkg/logtail/PluginAdapter.dll
  plugins/input/canal/input_canal.go
  scripts/plugin_build.sh
  test/case/behavior/input_mssql/Dockerfile
  test/case/behavior/input_mssql/docker-compose.yaml
  test/go.mod
  test/go.sum
Labels: bug

#1648 [backport 2.0] fix: GTID Truncation Issue and Improve Consistency in Checkpoint Management
  .github/workflows/build-pure-plugin.yaml
  go.mod
  go.sum
  licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
  pkg/logtail/PluginAdapter.dll
  plugins/input/canal/input_canal.go
  scripts/plugin_build.sh
  test/case/behavior/input_mssql/Dockerfile
  test/case/behavior/input_mssql/docker-compose.yaml
Labels: bug

#1636 feat: add loong collector monitor
  core/application/Application.cpp
  core/event_handler/LogInput.cpp
  core/event_handler/LogInput.h
  core/input/InputFile.cpp
  core/input/InputFile.h
  core/monitor/LogtailMetric.cpp
  core/monitor/LogtailMetric.h
  core/monitor/LoongCollectorMetricTypes.h
  core/monitor/MetricConstants.cpp
  core/monitor/MetricConstants.h
  core/monitor/Monitor.cpp
  core/monitor/Monitor.h
  core/monitor/PluginMetricManager.h
  core/polling/PollingDirFile.cpp
  core/polling/PollingDirFile.h
  core/polling/PollingModify.cpp
  core/polling/PollingModify.h
  core/processor/ProcessorSPL.cpp
  core/processor/ProcessorSPL.h
  core/processor/daemon/LogProcess.cpp
  core/processor/daemon/LogProcess.h
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
  core/sender/Sender.cpp
  core/sender/Sender.h
  core/unittest/monitor/PluginMetricManagerUnittest.cpp
Labels: enhancement

#1645 upgrade development image
  .devcontainer/Dockerfile
  config_server/service/Dockerfile
  core/dependencies.cmake
  docker/Dockerfile.ilogtail-build-linux
  docker/Dockerfile.ilogtail-toolchain-linux
  docker/Dockerfile_build
  docker/Dockerfile_coverage
  docker/Dockerfile_development_part
  docker/Dockerfile_goc
  docker/build-multi-arch-build-image.sh
Labels: miscellaneous

#1649 suicide immediately when resource hard limit is met
  core/monitor/Monitor.cpp
  core/monitor/Monitor.h
Labels: enhancement

#1633 Support config server v2 provider
  core/CMakeLists.txt
  core/application/Application.cpp
  core/application/Application.h
  core/config/provider/CommonConfigProvider.cpp
  core/config/provider/CommonConfigProvider.h
  core/config/provider/LegacyCommonConfigProvider.cpp
  core/config/provider/LegacyCommonConfigProvider.h
  core/dependencies.cmake
  core/pipeline/PipelineManager.h
  core/pipeline/ProcessConfigManager.h
  core/unittest/config/CMakeLists.txt
  core/unittest/config/CommonConfigProviderUnittest.cpp
  core/unittest/queue/SenderQueueUnittest.cpp
  docker/Dockerfile_e2e
  docker/build-multi-arch-build-image.sh
  docs/cn/developer-guide/development-environment.md
Labels: feature request
