Repository alibaba/loongcollector, pull requests merged in 2024-06, with the labels that each got.

#1528 fix: disable nanosecond timestamp when only EnableTimestampNanosecond is enabled
  core/common/TimeUtil.cpp
  core/common/TimeUtil.h
  core/models/LogEvent.cpp
  core/models/MetricEvent.cpp
  core/models/PipelineEvent.h
  core/models/SpanEvent.cpp
  core/processor/daemon/LogProcess.cpp
  core/spl/PipelineEventGroupInput.cpp
  core/unittest/models/MetricEventUnittest.cpp
  core/unittest/models/SpanEventUnittest.cpp
  core/unittest/processor/ProcessorMergeMultilineLogNativeUnittest.cpp
  core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
  core/unittest/processor/ProcessorParseRegexNativeUnittest.cpp
Labels: bug

#1529 fix core caused by empty container log path
  core/input/InputContainerStdio.cpp
  pkg/helper/mount_others.go
Labels: bug

#1516 add config server proto v2
  config_server/protocol/README.md
  config_server/protocol/v1/agent.proto
  config_server/protocol/v1/user.proto
  config_server/protocol/v2/README.md
  config_server/protocol/v2/agent.proto
  docs/cn/config-server/developer-guide.md
Labels: feature request

#1530 make inner processors input-dependent resources instead of pipeline-dependent ones
  core/config/Config.h
  core/file_server/FileDiscoveryOptions.cpp
  core/file_server/MultilineOptions.cpp
  core/input/InputContainerStdio.cpp
  core/input/InputContainerStdio.h
  core/input/InputFile.cpp
  core/input/InputFile.h
  core/input/InputObserverNetwork.cpp
  core/input/InputObserverNetwork.h
  core/pipeline/Pipeline.cpp
  core/pipeline/Pipeline.h
  core/pipeline/PipelineContext.h
  core/plugin/PluginRegistry.h
  core/plugin/instance/InputInstance.cpp
  core/plugin/instance/InputInstance.h
  core/plugin/instance/ProcessorInstance.h
  core/plugin/interface/Input.h
  core/processor/daemon/LogProcess.cpp
  core/unittest/config/ConfigUnittest.cpp
  core/unittest/input/InputContainerStdioUnittest.cpp
  core/unittest/input/InputFileUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
  core/unittest/plugin/InputInstanceUnittest.cpp
  core/unittest/plugin/PluginMock.h
  core/unittest/plugin/ProcessorInstanceUnittest.cpp
Labels: enhancement, core

#1509 Add UseDecimal parameter to the service_canal plugin. When UseDecimal is set to true, the binlog parsing outputs the original DECIMAL format instead of scientific notation
  docs/cn/plugins/input/service-canal.md
  plugins/input/canal/input_canal.go
Labels: bug

#1539 refactor sender queue item
  core/common/LogGroupContext.h
  core/common/LogstoreSenderQueue.h
  core/flusher/FlusherSLS.cpp
  core/flusher/FlusherSLS.h
  core/monitor/LogFileProfiler.h
  core/monitor/LogIntegrity.cpp
  core/monitor/LogIntegrity.h
  core/monitor/LogLineCount.cpp
  core/monitor/LogLineCount.h
  core/plugin/interface/Flusher.h
  core/processor/ProcessorFilterNative.cpp
  core/processor/ProcessorFilterNative.h
  core/profile_sender/ProfileSender.cpp
  core/queue/SenderQueueItem.cpp
  core/queue/SenderQueueItem.h
  core/sender/Sender.cpp
  core/sender/Sender.h
  core/serializer/SLSSerializer.cpp
  core/unittest/common/CMakeLists.txt
  core/unittest/flusher/FlusherSLSUnittest.cpp
  core/unittest/serializer/SLSSerializerUnittest.cpp
Labels: enhancement, core

#1544 fix: revert missing splitline of shennong log profile in processorsplitmultilinelog
  core/processor/inner/ProcessorMergeMultilineLogNative.cpp
  core/processor/inner/ProcessorSplitLogStringNative.cpp
  core/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
Labels: bug

#1485 refactor: add variable label value to self metric apis
  docs/cn/SUMMARY.md
  docs/cn/developer-guide/plugin-development/plugin-self-monitor-guide.md
  go.mod
  go.sum
  pkg/helper/local_context.go
  pkg/helper/log_file_reader.go
  pkg/helper/log_helper.go
  pkg/helper/log_helper_test.go
  pkg/helper/math_helper.go
  pkg/helper/math_helper_test.go
  pkg/helper/pool_helper.go
  pkg/helper/pool_helper_test.go
  pkg/helper/self_metric_imp.go
  pkg/helper/self_metric_imp_test.go
  pkg/helper/self_metrics_v2_imp.go
  pkg/helper/self_metrics_v2_imp_test.go
  pkg/helper/self_metrics_vector_imp.go
  pkg/helper/self_metrics_vector_imp_test.go
  pkg/pipeline/context.go
  pkg/pipeline/plugin.go
  pkg/pipeline/self_metric.go
  pkg/pipeline/self_metrics.go
  pluginmanager/context_imp.go
  pluginmanager/logstore_config.go
  pluginmanager/metric_wrapper.go
  pluginmanager/plugin_runner_helper.go
  pluginmanager/plugin_runner_v1.go
  pluginmanager/plugin_runner_v2.go
  pluginmanager/self_telemetry_statistics.go
  plugins/flusher/sls/flusher_sls.go
  plugins/input/canal/input_canal.go
  plugins/input/docker/logmeta/metric_container_info.go
  plugins/input/docker/stdout/input_docker_stdout.go
  plugins/input/mysql/mysql.go
  plugins/input/rdb/rdb.go
  plugins/processor/anchor/anchor.go
  plugins/processor/droplastkey/processor_drop_last_key.go
  plugins/processor/encrypt/processor_encrypt.go
  plugins/processor/fieldswithcondition/processor_fields_with_condition.go
  plugins/processor/filter/keyregex/processor_filter_key_regex.go
  plugins/processor/filter/regex/processor_filter_regex.go
  plugins/processor/pickkey/processor_pick_key.go
  plugins/processor/ratelimit/processor_rate_limit.go
  plugins/processor/ratelimit/processor_rate_limit_test.go
  plugins/processor/regex/regex.go
  plugins/processor/stringreplace/processor_string_replace.go
  plugins/test/mock/context.go
  test/engine/controller/validator_control.go
  test/engine/validator/validator.go
Labels: feature request

#1548 relax pipeline topology restriction
  core/config/Config.cpp
  core/go_pipeline/LogtailPlugin.cpp
  core/pipeline/Pipeline.cpp
Labels: enhancement, core

#1547 support shallow copy for event group
  core/models/LogEvent.cpp
  core/models/LogEvent.h
  core/models/MetricEvent.cpp
  core/models/MetricEvent.h
  core/models/PipelineEvent.h
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/models/PipelineEventPtr.h
  core/models/SpanEvent.cpp
  core/models/SpanEvent.h
  core/pipeline/Pipeline.cpp
  core/unittest/models/PipelineEventGroupUnittest.cpp
  core/unittest/models/PipelineEventPtrUnittest.cpp
Labels: enhancement, core

#1568 make reader flush timeout adjustable globally
  core/config_manager/ConfigManagerBase.cpp
Labels: bug
