Repository alibaba/loongcollector, pull requests merged in 2024-04, with the labels that each got.

#1429 fix: update base image to resolve 'Illegal instruction' error on old CPUs
  .devcontainer/Dockerfile
  config_server/service/Dockerfile
  docker/Dockerfile.ilogtail-build-linux
  docker/Dockerfile_build
  docker/Dockerfile_development_part
  docker/Dockerfile_goc
Labels: bug

#1444 fix missing user agent info
  core/sender/Sender.cpp
Labels: bug

#1443 fix plugin alarm with default version
  scripts/plugin_build.sh
Labels: bug

#1440 fix: make LOGTAIL_LOG_LEVEL env variable effective for ilogtail.LOG
  core/logger/Logger.cpp
Labels: bug

#1432 test: add a case to test timeformat without year
  core/unittest/processor/ProcessorParseTimestampNativeUnittest.cpp
Labels: test

#1430 Fix parameter errors for container metadata preview.
  pluginmanager/container_config_manager.go
  pluginmanager/logstore_config.go
  plugins/input/docker/logmeta/metric_docker_file.go
Labels: bug

#1456 fix: normalize logpath to avoid crash during handler registration
  core/common/FileSystemUtil.cpp
  core/config_manager/ConfigManagerBase.cpp
  core/unittest/common/FileSystemUtilUnittest.h
Labels: bug

#1449 feat: rate limit for history file import
  core/event_handler/HistoryFileImporter.cpp
  core/event_handler/HistoryFileImporter.h
  core/event_handler/LogInput.cpp
  core/unittest/CMakeLists.txt
  core/unittest/event_handler/CMakeLists.txt
  core/unittest/event_handler/HistoryFileImporterUnittest.cpp
  docs/cn/data-pipeline/input/history-log.md
Labels: enhancement

#1457 refactory: enable move for SourceBuffer
  core/common/CMakeLists.txt
  core/common/EncodingConverter.h
  core/common/memory/SourceBuffer.h
  core/models/PipelineEvent.h
  core/models/PipelineEventGroup.h
  core/monitor/LogIntegrity.h
  core/processor/daemon/LogProcess.cpp
  core/reader/LogFileReader.cpp
  core/reader/LogFileReader.h
  core/unittest/reader/LogFileReaderUnittest.cpp
  core/unittest/reader/RemoveLastIncompleteLogUnittest.cpp
Labels: enhancement

#1460 document: fix document for flusher pulsar
  docs/cn/configuration/collection-config.md
  docs/cn/plugins/flusher/flusher-pulsar.md
Labels: documentation

#1448 enhancement: boost multiline and docker log parsing performance
  core/common/StringTools.cpp
  core/common/StringTools.h
  core/file_server/MultilineOptions.cpp
  core/input/InputContainerLog.cpp
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/pipeline/Pipeline.cpp
  core/processor/ProcessorMergeMultilineLogNative.cpp
  core/processor/ProcessorMergeMultilineLogNative.h
  core/processor/ProcessorParseContainerLogNative.cpp
  core/processor/ProcessorParseContainerLogNative.h
  core/processor/ProcessorSplitMultilineLogStringNative.cpp
  core/reader/LogFileReader.cpp
  core/unittest/common/StringToolsUnittest.cpp
  core/unittest/processor/BoostRegexBenchmark.cpp
  core/unittest/processor/CMakeLists.txt
  core/unittest/processor/ParseContainerLogBenchmark.cpp
  core/unittest/processor/ProcessorParseContainerLogNativeUnittest.cpp
Labels: enhancement

#1465 improve worst case performance when all events failed to process
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/processor/ProcessorFilterNative.cpp
  core/processor/ProcessorParseApsaraNative.cpp
  core/processor/ProcessorParseDelimiterNative.cpp
  core/processor/ProcessorParseJsonNative.cpp
  core/processor/ProcessorParseRegexNative.cpp
  core/processor/ProcessorParseTimestampNative.cpp
  core/unittest/models/CMakeLists.txt
  core/unittest/models/EventGroupBenchmark.cpp
Labels: enhancement
