Repository alibaba/loongcollector, pull requests merged in 2024-12, with the labels that each got.

#1968 fix event pool unittest memory leak
  core/unittest/models/CMakeLists.txt
  core/unittest/models/EventPoolUnittest.cpp
Labels: miscellaneous

#1967 block tmp dir for inotify
  core/CMakeLists.txt
  core/app_config/AppConfig.cpp
Labels: enhancement

#1974 fix: config watcher ut
  core/unittest/config/ConfigUpdateUnittest.cpp
  core/unittest/config/PipelineConfigWatcherUnittest.cpp
Labels: test
