Repository alibaba/loongcollector, pull requests merged in 2024-03, with the labels that each got.

#1368 polish pipelineEvent and pipelineEventPtr class to improve performance
  core/models/LogEvent.cpp
  core/models/LogEvent.h
  core/models/MetricEvent.cpp
  core/models/MetricEvent.h
  core/models/PipelineEvent.cpp
  core/models/PipelineEvent.h
  core/models/PipelineEventGroup.cpp
  core/models/PipelineEventGroup.h
  core/models/PipelineEventPtr.h
  core/models/SpanEvent.cpp
  core/models/SpanEvent.h
  core/pipeline/Pipeline.h
  core/processor/ProcessorSplitLogStringNative.cpp
  core/processor/ProcessorSplitLogStringNative.h
  core/processor/ProcessorSplitRegexNative.cpp
  core/processor/ProcessorSplitRegexNative.h
  core/processor/daemon/LogProcess.cpp
  core/spl/PipelineEventGroupInput.cpp
  core/spl/PipelineEventGroupOutput.cpp
  core/unittest/models/LogEventUnittest.cpp
  core/unittest/models/PipelineEventGroupUnittest.cpp
  core/unittest/models/PipelineEventPtrUnittest.cpp
  core/unittest/models/PipelineEventUnittest.cpp
  core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
  core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
  core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
  core/unittest/processor/ProcessorParseRegexNativeUnittest.cpp
  core/unittest/processor/ProcessorParseTimestampNativeUnittest.cpp
  core/unittest/processor/ProcessorSplitLogStringNativeUnittest.cpp
  core/unittest/processor/ProcessorSplitRegexNativeUnittest.cpp
Labels: enhancement

#1394 Fix: Add flusher_stdout Tags parameter in document examples
  docs/cn/getting-started/k8slog-collect-to-sls.md
  docs/cn/installation/start-with-k8s.md
  docs/cn/plugins/flusher/flusher-stdout.md
  docs/cn/plugins/input/input-file.md
  k8s_templates/ilogtail-daemonset-file-to-sls.yaml
  k8s_templates/ilogtail-daemonset-stdout-to-sls.yaml
  k8s_templates/ilogtail-sidecar-file-to-sls.yaml
Labels: documentation

#1408 fix: maintain sequential info of the original log content and allow multivalue for single key for apsara processor
  core/models/LogEvent.cpp
  core/models/LogEvent.h
  core/processor/CommonParserOptions.cpp
  core/processor/ProcessorDesensitizeNative.cpp
  core/processor/ProcessorFilterNative.cpp
  core/processor/ProcessorFilterNative.h
  core/processor/ProcessorParseApsaraNative.cpp
  core/processor/ProcessorSplitLogStringNative.cpp
  core/processor/ProcessorSplitRegexNative.cpp
  core/processor/daemon/LogProcess.cpp
  core/unittest/models/LogEventUnittest.cpp
Labels: bug

#1395 feat: add full_drain_mode option to ensure complete data flush over network before shutdown
  core/aggregator/Aggregator.cpp
  core/application/Application.h
  core/common/LogtailCommonFlags.cpp
  core/common/LogtailCommonFlags.h
  core/controller/EventDispatcher.cpp
  core/controller/EventDispatcher.h
  core/event_handler/EventHandler.cpp
  core/event_handler/EventHandler.h
  core/event_handler/LogInput.cpp
  core/event_handler/LogInput.h
  core/pipeline/PipelineManager.cpp
  core/sender/Sender.cpp
Labels: enhancement

#1413 fix: read length meta bug due to key typo
  core/processor/daemon/LogProcess.cpp
Labels: bug

#1419 [backport] Improve sender log condition to record valuable debug info
  core/common/LogFileCollectOffsetIndicator.cpp
  core/common/LogstoreSenderQueue.cpp
  core/common/LogstoreSenderQueue.h
  core/monitor/LogIntegrity.cpp
  core/sender/Sender.cpp
Labels: enhancement

#1424 fix dockershim cause containerd invalid
  pkg/helper/docker_cri_adapter.go
Labels: bug

#1422 [backport] fix dockershim cause containerd invalid
  pkg/helper/docker_cri_adapter.go
Labels: bug

#1427 fix: correct pipeline version recognition issue
  pluginmanager/logstore_config.go
  plugins/flusher/stdout/flusher_stdout.go
Labels: bug
