Repository alibaba/loongcollector, pull requests merged in 2025-02, with the labels that each got.

#2068 ignore EnableContainerDiscovery if not in container for backward compatability
  core/input/InputFile.cpp
  core/plugin/PluginRegistry.cpp
  core/unittest/input/InputFileUnittest.cpp
  plugins/input/netping/netping_test.go
Labels: bug

#2076 Fix typos
  core/common/FileSystemUtil.cpp
  core/common/LRUCache.h
  core/common/Lock.h
  core/common/LogFileOperator.h
  core/common/MachineInfoUtil.cpp
  core/common/TimeUtil.h
  core/common/http/Curl.cpp
  core/models/PipelineEventGroup.h
  core/prometheus/labels/TextParser.cpp
  core/unittest/config/ConfigMatchUnittest.cpp
  core/unittest/config/ConfigUpdatorUnittest.cpp
  core/unittest/polling/PollingUnittest.cpp
  core/unittest/processor/ProcessorFilterNativeUnittest.cpp
  core/unittest/queue/SenderQueueManagerUnittest.cpp
  core/unittest/sender/SenderUnittest.cpp
Labels: miscellaneous

#2113 [backport] feat: support set TOS in curl
  core/sdk/CurlImp.cpp
Labels: feature
