Repository alibaba/loongcollector, pull requests merged in 2025-01, with the labels that each got.

#2006 fix: remove legacy code in Prom Parse Processor
  core/plugin/processor/inner/ProcessorPromParseMetricNative.cpp
Labels: miscellaneous

#2016 [backport 2.0] fix the issue where flusher_sls does not work when coexisting with extended flushers && core caused by invalid flusher_sls pointer in enterprise mode
  core/flusher/FlusherSLS.cpp
  core/pipeline/Pipeline.cpp
  core/pipeline/PipelineContext.h
  core/unittest/config/ConfigUnittest.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
Labels: bug

#2015 fix the issue where flusher_sls does not work when coexisting with extended flushers
  core/pipeline/Pipeline.cpp
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/unittest/config/PipelineConfigUnittest.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
  core/unittest/pipeline/PipelineUnittest.cpp
Labels: bug

#2017 flusher_otlp: Ensure headers are correctly passed when sending data
  plugins/flusher/opentelemetry/flusher_otlp.go
Labels: bug

#2024 fix ut: http mock server protects the result slice with lock
  plugins/flusher/prometheus/flusher_prometheus_test.go
Labels: bug

#2018 feat: prom support drop metrics and external_labels
  core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
  core/prometheus/Constants.h
  core/prometheus/labels/Relabel.cpp
  core/prometheus/labels/Relabel.h
  core/prometheus/schedulers/ScrapeConfig.cpp
  core/prometheus/schedulers/ScrapeConfig.h
  core/unittest/processor/ProcessorPromRelabelMetricNativeUnittest.cpp
  core/unittest/prometheus/RelabelUnittest.cpp
  core/unittest/prometheus/ScrapeConfigUnittest.cpp
Labels: enhancement

#2029 disable group batch when flusher_sls.telemetrytype equals metrics
  core/plugin/flusher/sls/FlusherSLS.cpp
  core/unittest/flusher/FlusherSLSUnittest.cpp
Labels: bug

#2044 chore: update CI base image
  config_server/service/Dockerfile
  docker/Dockerfile_build
  docker/Dockerfile_coverage
  docker/Dockerfile_development_part
  docker/Dockerfile_e2e
  docker/Dockerfile_goc
  docker/Dockerfile_production
  docs/cn/developer-guide/development-environment.md
  docs/cn/installation/release-notes/release-notes.md
Labels: miscellaneous

#2041 fix enable containerd upper dir detect not effective
  core/common/LogtailCommonFlags.cpp
  core/go_pipeline/LogtailPlugin.cpp
  core/logtail.cpp
  core/logtail_windows.cpp
  docs/cn/installation/start-with-k8s.md
  pkg/config/global_config.go
  pkg/flags/flags.go
  pkg/helper/docker_cri_adapter.go
Labels: bug

#2034 allowing for the forced release of stopped container files based on an environment variable(FORCE_RELEASE_STOP_CONTAINER_FILE)
  plugins/input/docker/logmeta/metric_container_info.go
Labels: enhancement
